// Code generated by goplus from sel.gp. DO NOT EDIT.
//goplus:v v0.28.0

package tui

import (
	"fmt"
	"strings"

	tea "charm.land/bubbletea/v2"
	"goforge.dev/cadence/program"
	"goforge.dev/cadence/sel"
)

func RenderSEL[Msg any](root sel.Element[Msg], palette Palette) (string, error) {
	if err := sel.Validate(root, sel.TargetTerminal{}); err != nil {
		return "", err
	}
	return renderElement(root, palette)
}

func SELView[State any, Msg any](
	render func(State) sel.Element[Msg],
	palette Palette,
) program.View[State, Msg, tea.View] {
	return func(state State) tea.View {
		content, err := RenderSEL(render(state), palette)
		if err != nil {
			return tea.NewView("render error: " + err.Error())
		}
		return tea.NewView(content)
	}
}

func renderElement[Msg any](element sel.Element[Msg], palette Palette) (string, error) {
	children := make([]string, 0, len(element.Children))
	for _, child := range element.Children {
		rendered, err := renderElement(child, palette)
		if err != nil {
			return "", err
		}
		children = append(children, rendered)
	}
	name := sel.KindName(element.Kind)
	var content string
	switch name {
	case "text", "heading", "status":
		content = element.Text
	case "paragraph", "column", "stack", "scroll", "form":
		content = strings.Join(children, "\n")
	case "row":
		content = strings.Join(children, " ")
	case "link":
		content = strings.Join(children, "") + " <" + element.Attributes["href"] + ">"
	case "button":
		content = "[ " + strings.Join(children, "") + " ]"
	case "text-input", "text-area":
		content = element.Description + ": " + element.Value
	case "checkbox":
		mark := " "
		if element.Checked {
			mark = "x"
		}
		content = "[" + mark + "] " + strings.Join(children, "")
	case "select":
		content = element.Description + ": " + element.Value
	case "list":
		for index := range children {
			children[index] = "- " + children[index]
		}
		content = strings.Join(children, "\n")
	case "table":
		content = strings.Join(children, "\n")
	case "image":
		content = "[image: " + element.Description + "]"
	case "progress":
		content = fmt.Sprintf(
			"%s %s/%s",
			element.Description,
			element.Attributes["value"],
			element.Attributes["max"],
		)
	default:
		content = strings.Join(children, "\n")
	}
	if element.Disabled {
		content = content + " (disabled)"
	}
	if element.Style.Hidden {
		return "", nil
	}
	return LowerStyle(element.Style, palette).Render(content), nil
}
