// Code generated by goplus from command.gp. DO NOT EDIT.
//goplus:v v0.28.0

package browser

import (
	"encoding/json"
	"fmt"

	"goforge.dev/cadence/program"
)

const CommandProtocolVersion = 1
const RemoteEffectName = "cadence.remote.v1"

type CommandRequest struct {
	ProtocolVersion int             `json:"protocol_version"`
	AppID           string          `json:"app_id"`
	ProgramID       string          `json:"program_id"`
	InstanceID      string          `json:"instance_id"`
	RequestID       string          `json:"request_id"`
	Command         string          `json:"command"`
	Revision        uint64          `json:"revision"`
	Payload         json.RawMessage `json:"payload"`
}

type PublicError struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable"`
}

type CommandResponse struct {
	ProtocolVersion int             `json:"protocol_version"`
	RequestID       string          `json:"request_id"`
	Revision        uint64          `json:"revision"`
	Result          json.RawMessage `json:"result,omitempty"`
	Error           *PublicError    `json:"error,omitempty"`
}

// RemoteEffect is the erased, typed response mapping carried by a network
// command. Application code constructs it only through Remote.
type RemoteEffect[Msg any] struct {
	RequestID string
	Command   string
	Payload   json.RawMessage
	Success   func(json.RawMessage) (Msg, error)
	Failure   func(PublicError) Msg
}

func Remote[Request any, Response any, Msg any](
	requestID, command string,
	request Request,
	success func(Response) Msg,
	failure func(PublicError) Msg,
) (program.Cmd[Msg], error) {
	if requestID == "" || command == "" || success == nil || failure == nil {
		return program.None[Msg](), fmt.Errorf(
			"quicken/web/browser: remote request ID, command, and mappings are required",
		)
	}
	payload, err := json.Marshal(request)
	if err != nil {
		return program.None[Msg](), err
	}
	effect := RemoteEffect[Msg]{
		RequestID: requestID,
		Command:   command,
		Payload:   payload,
		Success: func(raw json.RawMessage) (Msg, error) {
			var response Response
			if err := json.Unmarshal(raw, &response); err != nil {
				var zero Msg
				return zero, err
			}
			return success(response), nil
		},
		Failure: failure,
	}
	return program.Effect[Msg](
		requestID,
		program.CapabilityNetwork{},
		RemoteEffectName,
		effect,
	), nil
}

func MustRemote[Request any, Response any, Msg any](
	requestID, command string,
	request Request,
	success func(Response) Msg,
	failure func(PublicError) Msg,
) program.Cmd[Msg] {
	cmd, err := Remote(requestID, command, request, success, failure)
	if err != nil {
		panic(err)
	}
	return cmd
}
