// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package browser is the typed browser view, SSR, hydration-manifest, and DOM
// patch substrate for Cadence programs. The syscall/js interpreter lives in
// the dom subpackage so server renderers remain portable.
package browser
