// Code generated by goplus from node.gp. DO NOT EDIT.
//goplus:v v0.28.0

package browser

import "goforge.dev/cadence/style"

//goplus:enum NodeKind
type NodeKind interface{ isNodeKind() }

//goplus:variant (NodeKind) NodeElement
type NodeElement struct{}

func (NodeElement) isNodeKind() {}

//goplus:variant (NodeKind) NodeText
type NodeText struct{}

func (NodeText) isNodeKind() {}

//goplus:variant (NodeKind) NodeFragment
type NodeFragment struct{}

func (NodeFragment) isNodeKind() {}

// NodeKindCases selects one handler per NodeKind variant for NodeKindFold.
type NodeKindCases[R any] struct {
	NodeElement  func() R
	NodeText     func() R
	NodeFragment func() R
}

// NodeKindFold reduces NodeKind by one-level case analysis.
func NodeKindFold[R any](n NodeKind, cs NodeKindCases[R]) R {
	switch any(n).(type) {
	case NodeElement:
		return cs.NodeElement()
	case NodeText:
		return cs.NodeText()
	case NodeFragment:
		return cs.NodeFragment()
	default:
		panic("goplus: impossible enum value in NodeKindFold")
	}
}

// NodeKindEqOverrides carries optional per-variant hooks for NodeKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type NodeKindEqOverrides struct {
	NodeElement  func(x, y NodeElement) (eq, handled bool)
	NodeText     func(x, y NodeText) (eq, handled bool)
	NodeFragment func(x, y NodeFragment) (eq, handled bool)
}

// NodeKindEqualWith reports structural equality of a and b under ov.
func NodeKindEqualWith(a, b NodeKind, ov NodeKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case NodeElement:
		y, ok := any(b).(NodeElement)
		if !ok {
			return false
		}
		if ov.NodeElement != nil {
			if eq, handled := ov.NodeElement(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NodeText:
		y, ok := any(b).(NodeText)
		if !ok {
			return false
		}
		if ov.NodeText != nil {
			if eq, handled := ov.NodeText(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case NodeFragment:
		y, ok := any(b).(NodeFragment)
		if !ok {
			return false
		}
		if ov.NodeFragment != nil {
			if eq, handled := ov.NodeFragment(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// NodeKindEqual reports structural equality of a and b.
func NodeKindEqual(a, b NodeKind) bool {
	return NodeKindEqualWith(a, b, NodeKindEqOverrides{})
}

//goplus:enum AttributeKind
type AttributeKind interface{ isAttributeKind() }

//goplus:variant (AttributeKind) AttributeString
type AttributeString struct{}

func (AttributeString) isAttributeKind() {}

//goplus:variant (AttributeKind) AttributeProperty
type AttributeProperty struct{}

func (AttributeProperty) isAttributeKind() {}

//goplus:variant (AttributeKind) AttributeBoolean
type AttributeBoolean struct{}

func (AttributeBoolean) isAttributeKind() {}

// AttributeKindCases selects one handler per AttributeKind variant for AttributeKindFold.
type AttributeKindCases[R any] struct {
	AttributeString   func() R
	AttributeProperty func() R
	AttributeBoolean  func() R
}

// AttributeKindFold reduces AttributeKind by one-level case analysis.
func AttributeKindFold[R any](a AttributeKind, cs AttributeKindCases[R]) R {
	switch any(a).(type) {
	case AttributeString:
		return cs.AttributeString()
	case AttributeProperty:
		return cs.AttributeProperty()
	case AttributeBoolean:
		return cs.AttributeBoolean()
	default:
		panic("goplus: impossible enum value in AttributeKindFold")
	}
}

// AttributeKindEqOverrides carries optional per-variant hooks for AttributeKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type AttributeKindEqOverrides struct {
	AttributeString   func(x, y AttributeString) (eq, handled bool)
	AttributeProperty func(x, y AttributeProperty) (eq, handled bool)
	AttributeBoolean  func(x, y AttributeBoolean) (eq, handled bool)
}

// AttributeKindEqualWith reports structural equality of a and b under ov.
func AttributeKindEqualWith(a, b AttributeKind, ov AttributeKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case AttributeString:
		y, ok := any(b).(AttributeString)
		if !ok {
			return false
		}
		if ov.AttributeString != nil {
			if eq, handled := ov.AttributeString(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AttributeProperty:
		y, ok := any(b).(AttributeProperty)
		if !ok {
			return false
		}
		if ov.AttributeProperty != nil {
			if eq, handled := ov.AttributeProperty(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case AttributeBoolean:
		y, ok := any(b).(AttributeBoolean)
		if !ok {
			return false
		}
		if ov.AttributeBoolean != nil {
			if eq, handled := ov.AttributeBoolean(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// AttributeKindEqual reports structural equality of a and b.
func AttributeKindEqual(a, b AttributeKind) bool {
	return AttributeKindEqualWith(a, b, AttributeKindEqOverrides{})
}

type Attribute struct {
	Kind  AttributeKind
	Name  string
	Value string
}

//goplus:enum EventKind
type EventKind interface{ isEventKind() }

//goplus:variant (EventKind) EventClick
type EventClick struct{}

func (EventClick) isEventKind() {}

//goplus:variant (EventKind) EventInput
type EventInput struct{}

func (EventInput) isEventKind() {}

//goplus:variant (EventKind) EventChange
type EventChange struct{}

func (EventChange) isEventKind() {}

//goplus:variant (EventKind) EventSubmit
type EventSubmit struct{}

func (EventSubmit) isEventKind() {}

//goplus:variant (EventKind) EventFocus
type EventFocus struct{}

func (EventFocus) isEventKind() {}

//goplus:variant (EventKind) EventBlur
type EventBlur struct{}

func (EventBlur) isEventKind() {}

//goplus:variant (EventKind) EventKeyDown
type EventKeyDown struct{}

func (EventKeyDown) isEventKind() {}

//goplus:variant (EventKind) EventKeyUp
type EventKeyUp struct{}

func (EventKeyUp) isEventKind() {}

// EventKindCases selects one handler per EventKind variant for EventKindFold.
type EventKindCases[R any] struct {
	EventClick   func() R
	EventInput   func() R
	EventChange  func() R
	EventSubmit  func() R
	EventFocus   func() R
	EventBlur    func() R
	EventKeyDown func() R
	EventKeyUp   func() R
}

// EventKindFold reduces EventKind by one-level case analysis.
func EventKindFold[R any](e EventKind, cs EventKindCases[R]) R {
	switch any(e).(type) {
	case EventClick:
		return cs.EventClick()
	case EventInput:
		return cs.EventInput()
	case EventChange:
		return cs.EventChange()
	case EventSubmit:
		return cs.EventSubmit()
	case EventFocus:
		return cs.EventFocus()
	case EventBlur:
		return cs.EventBlur()
	case EventKeyDown:
		return cs.EventKeyDown()
	case EventKeyUp:
		return cs.EventKeyUp()
	default:
		panic("goplus: impossible enum value in EventKindFold")
	}
}

// EventKindEqOverrides carries optional per-variant hooks for EventKindEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type EventKindEqOverrides struct {
	EventClick   func(x, y EventClick) (eq, handled bool)
	EventInput   func(x, y EventInput) (eq, handled bool)
	EventChange  func(x, y EventChange) (eq, handled bool)
	EventSubmit  func(x, y EventSubmit) (eq, handled bool)
	EventFocus   func(x, y EventFocus) (eq, handled bool)
	EventBlur    func(x, y EventBlur) (eq, handled bool)
	EventKeyDown func(x, y EventKeyDown) (eq, handled bool)
	EventKeyUp   func(x, y EventKeyUp) (eq, handled bool)
}

// EventKindEqualWith reports structural equality of a and b under ov.
func EventKindEqualWith(a, b EventKind, ov EventKindEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case EventClick:
		y, ok := any(b).(EventClick)
		if !ok {
			return false
		}
		if ov.EventClick != nil {
			if eq, handled := ov.EventClick(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventInput:
		y, ok := any(b).(EventInput)
		if !ok {
			return false
		}
		if ov.EventInput != nil {
			if eq, handled := ov.EventInput(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventChange:
		y, ok := any(b).(EventChange)
		if !ok {
			return false
		}
		if ov.EventChange != nil {
			if eq, handled := ov.EventChange(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventSubmit:
		y, ok := any(b).(EventSubmit)
		if !ok {
			return false
		}
		if ov.EventSubmit != nil {
			if eq, handled := ov.EventSubmit(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventFocus:
		y, ok := any(b).(EventFocus)
		if !ok {
			return false
		}
		if ov.EventFocus != nil {
			if eq, handled := ov.EventFocus(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventBlur:
		y, ok := any(b).(EventBlur)
		if !ok {
			return false
		}
		if ov.EventBlur != nil {
			if eq, handled := ov.EventBlur(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventKeyDown:
		y, ok := any(b).(EventKeyDown)
		if !ok {
			return false
		}
		if ov.EventKeyDown != nil {
			if eq, handled := ov.EventKeyDown(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case EventKeyUp:
		y, ok := any(b).(EventKeyUp)
		if !ok {
			return false
		}
		if ov.EventKeyUp != nil {
			if eq, handled := ov.EventKeyUp(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// EventKindEqual reports structural equality of a and b.
func EventKindEqual(a, b EventKind) bool {
	return EventKindEqualWith(a, b, EventKindEqOverrides{})
}

// EventData is the browser-neutral input exposed to application decoders.
type EventData struct {
	Value    string
	Key      string
	Code     string
	Checked  bool
	AltKey   bool
	CtrlKey  bool
	MetaKey  bool
	ShiftKey bool
	Repeat   bool
}

// Event has a stable ID for delegated listener reconciliation. Decode turns
// browser-neutral data into the application's closed message type.
type Event[Msg any] struct {
	ID     string
	Kind   EventKind
	Decode func(EventData) Msg
}

// Node is the browser-native declarative tree. It contains no DOM handles.
type Node[Msg any] struct {
	Kind       NodeKind
	Key        string
	Tag        string
	Text       string
	Attributes []Attribute
	Events     []Event[Msg]
	Children   []Node[Msg]
	Style      style.Style
}

func Element[Msg any](tag string, children ...Node[Msg]) Node[Msg] {
	return Node[Msg]{
		Kind: NodeElement{}, Tag: tag,
		Children: cloneNodes(children), Style: style.Default(),
	}
}

func Text[Msg any](value string) Node[Msg] {
	return Node[Msg]{Kind: NodeText{}, Text: value, Style: style.Default()}
}

func Fragment[Msg any](children ...Node[Msg]) Node[Msg] {
	return Node[Msg]{
		Kind: NodeFragment{}, Children: cloneNodes(children),
		Style: style.Default(),
	}
}

func (n Node[Msg]) WithKey(key string) Node[Msg] {
	n.Key = key
	return n
}

func (n Node[Msg]) WithAttribute(name, value string) Node[Msg] {
	n.Attributes = appendAttribute(n.Attributes, Attribute{
		Kind: AttributeString{}, Name: name, Value: value,
	})
	return n
}

func (n Node[Msg]) WithProperty(name, value string) Node[Msg] {
	n.Attributes = appendAttribute(n.Attributes, Attribute{
		Kind: AttributeProperty{}, Name: name, Value: value,
	})
	return n
}

func (n Node[Msg]) WithBoolean(name string, value bool) Node[Msg] {
	if value {
		n.Attributes = appendAttribute(n.Attributes, Attribute{
			Kind: AttributeBoolean{}, Name: name, Value: "true",
		})
		return n
	}
	n.Attributes = removeAttribute(n.Attributes, AttributeBoolean{}, name)
	return n
}

func (n Node[Msg]) On(id string, kind EventKind, decode func(EventData) Msg) Node[Msg] {
	events := append([]Event[Msg](nil), n.Events...)
	events = append(events, Event[Msg]{ID: id, Kind: kind, Decode: decode})
	n.Events = events
	return n
}

func (n Node[Msg]) WithStyle(value style.Style) Node[Msg] {
	n.Style = value
	return n
}

func cloneNodes[Msg any](nodes []Node[Msg]) []Node[Msg] {
	return append([]Node[Msg](nil), nodes...)
}

func appendAttribute(attributes []Attribute, next Attribute) []Attribute {
	out := make([]Attribute, 0, len(attributes)+1)
	for _, current := range attributes {
		if current.Name == next.Name && attributeKindName(current.Kind) == attributeKindName(next.Kind) {
			continue
		}
		out = append(out, current)
	}
	return append(out, next)
}

func removeAttribute(attributes []Attribute, kind AttributeKind, name string) []Attribute {
	out := make([]Attribute, 0, len(attributes))
	for _, current := range attributes {
		if current.Name == name && attributeKindName(current.Kind) == attributeKindName(kind) {
			continue
		}
		out = append(out, current)
	}
	return out
}

func nodeKindName(kind NodeKind) string {
	name := ""
	switch any(kind).(type) {
	case NodeElement:

		name = "element"
	case NodeText:

		name = "text"
	case NodeFragment:

		name = "fragment"
	default:
		panic("goplus: impossible enum value in match")
	}
	return name
}

func NodeKindName(kind NodeKind) string { return nodeKindName(kind) }

func attributeKindName(kind AttributeKind) string {
	name := ""
	switch any(kind).(type) {
	case AttributeString:

		name = "attribute"
	case AttributeProperty:

		name = "property"
	case AttributeBoolean:

		name = "boolean"
	default:
		panic("goplus: impossible enum value in match")
	}
	return name
}

func AttributeKindName(kind AttributeKind) string { return attributeKindName(kind) }

func EventKindName(kind EventKind) string {
	name := ""
	switch any(kind).(type) {
	case EventClick:

		name = "click"
	case EventInput:

		name = "input"
	case EventChange:

		name = "change"
	case EventSubmit:

		name = "submit"
	case EventFocus:

		name = "focus"
	case EventBlur:

		name = "blur"
	case EventKeyDown:

		name = "keydown"
	case EventKeyUp:

		name = "keyup"
	default:
		panic("goplus: impossible enum value in match")
	}
	return name
}
