// Code generated by goplus from command.gp. DO NOT EDIT.
//goplus:v v0.28.0

package quicken

import (
	"context"
	"crypto/subtle"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"
	"sync"

	browser "goforge.dev/quicken/web/browser"
)

const CommandProtocolVersion = browser.CommandProtocolVersion

type (
	CommandRequest  = browser.CommandRequest
	PublicError     = browser.PublicError
	CommandResponse = browser.CommandResponse
)

type erasedCommand interface {
	Invoke(context.Context, json.RawMessage) (json.RawMessage, *PublicError)
}

type typedCommand[Request any, Response any] struct {
	handler func(context.Context, Request) (Response, error)
	public  func(error) PublicError
}

func (c typedCommand[Request, Response]) Invoke(
	ctx context.Context,
	payload json.RawMessage,
) (json.RawMessage, *PublicError) {
	var request Request
	if err := json.Unmarshal(payload, &request); err != nil {
		failure := PublicError{
			Code: "invalid-payload", Message: "command payload is invalid",
		}
		return nil, &failure
	}
	response, err := c.handler(ctx, request)
	if err != nil {
		failure := PublicError{
			Code: "command-failed", Message: "command failed",
		}
		if c.public != nil {
			failure = c.public(err)
		}
		return nil, &failure
	}
	encoded, err := json.Marshal(response)
	if err != nil {
		failure := PublicError{
			Code: "encoding-failed", Message: "command response could not be encoded",
		}
		return nil, &failure
	}
	return encoded, nil
}

type CommandSet struct {
	handlers map[string]erasedCommand
}

func NewCommandSet() *CommandSet {
	return &CommandSet{handlers: map[string]erasedCommand{}}
}

func RegisterCommand[Request any, Response any](
	set *CommandSet,
	name string,
	handler func(context.Context, Request) (Response, error),
	public func(error) PublicError,
) {
	if set == nil || name == "" || handler == nil {
		panic("quicken: command set, name, and handler must be non-nil")
	}
	if _, exists := set.handlers[name]; exists {
		panic("quicken: duplicate command " + name)
	}
	set.handlers[name] = typedCommand[Request, Response]{
		handler: handler, public: public,
	}
}

type ReplayStore interface {
	Load(instanceID, requestID string) ([]byte, bool)
	Store(instanceID, requestID string, response []byte)
}

type MemoryReplayStore struct {
	mu       sync.Mutex
	capacity int
	order    []string
	values   map[string][]byte
}

func NewMemoryReplayStore(capacity int) *MemoryReplayStore {
	if capacity <= 0 {
		panic("quicken: replay capacity must be positive")
	}
	return &MemoryReplayStore{
		capacity: capacity,
		values:   map[string][]byte{},
	}
}

func (s *MemoryReplayStore) Load(instanceID, requestID string) ([]byte, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	value, ok := s.values[replayKey(instanceID, requestID)]
	return append([]byte(nil), value...), ok
}

func (s *MemoryReplayStore) Store(instanceID, requestID string, response []byte) {
	s.mu.Lock()
	defer s.mu.Unlock()
	key := replayKey(instanceID, requestID)
	if _, exists := s.values[key]; !exists {
		s.order = append(s.order, key)
	}
	s.values[key] = append([]byte(nil), response...)
	for len(s.order) > s.capacity {
		oldest := s.order[0]
		s.order = s.order[1:]
		delete(s.values, oldest)
	}
}

func replayKey(instanceID, requestID string) string {
	return instanceID + "\x00" + requestID
}

type BrowserSecurity struct {
	ValidateOrigin func(*http.Request) error
	ValidateCSRF   func(*http.Request) error
}

func DefaultBrowserSecurity() BrowserSecurity {
	return BrowserSecurity{
		ValidateOrigin: validateSameOrigin,
		ValidateCSRF:   validateDoubleSubmitCSRF,
	}
}

type CommandEndpoint struct {
	AppID     string
	ProgramID string
	Commands  *CommandSet
	Replay    ReplayStore
	Security  BrowserSecurity
	MaxBytes  int64
}

func (e CommandEndpoint) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	if req.Method != http.MethodPost {
		w.Header().Set("Allow", http.MethodPost)
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if err := e.validate(); err != nil {
		http.Error(w, "command endpoint unavailable", http.StatusInternalServerError)
		return
	}
	if err := e.Security.ValidateOrigin(req); err != nil {
		http.Error(w, "origin rejected", http.StatusForbidden)
		return
	}
	if err := e.Security.ValidateCSRF(req); err != nil {
		http.Error(w, "csrf rejected", http.StatusForbidden)
		return
	}
	limit := e.MaxBytes
	if limit <= 0 {
		limit = 1 << 20
	}
	req.Body = http.MaxBytesReader(w, req.Body, limit)
	var command CommandRequest
	decoder := json.NewDecoder(req.Body)
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&command); err != nil {
		http.Error(w, "invalid command request", http.StatusBadRequest)
		return
	}
	if err := validateCommandRequest(command, e.AppID, e.ProgramID); err != nil {
		http.Error(w, "invalid command request", http.StatusBadRequest)
		return
	}
	if cached, ok := e.Replay.Load(command.InstanceID, command.RequestID); ok {
		writeCommandResponse(w, cached)
		return
	}
	handler, ok := e.Commands.handlers[command.Command]
	if !ok {
		http.Error(w, "unknown command", http.StatusNotFound)
		return
	}
	result, publicError := handler.Invoke(req.Context(), command.Payload)
	response := CommandResponse{
		ProtocolVersion: CommandProtocolVersion,
		RequestID:       command.RequestID,
		Revision:        command.Revision,
		Result:          result,
		Error:           publicError,
	}
	encoded, err := json.Marshal(response)
	if err != nil {
		http.Error(w, "command response failed", http.StatusInternalServerError)
		return
	}
	e.Replay.Store(command.InstanceID, command.RequestID, encoded)
	writeCommandResponse(w, encoded)
}

func (e CommandEndpoint) validate() error {
	if e.AppID == "" || e.ProgramID == "" || e.Commands == nil || e.Replay == nil {
		return fmt.Errorf("quicken: command endpoint identity, registry, and replay store are required")
	}
	if e.Security.ValidateOrigin == nil || e.Security.ValidateCSRF == nil {
		return fmt.Errorf("quicken: command endpoint security validators are required")
	}
	return nil
}

func validateCommandRequest(command CommandRequest, appID, programID string) error {
	if command.ProtocolVersion != CommandProtocolVersion {
		return fmt.Errorf("unsupported protocol")
	}
	if command.AppID != appID || command.ProgramID != programID {
		return fmt.Errorf("command identity mismatch")
	}
	if command.InstanceID == "" || command.RequestID == "" || command.Command == "" {
		return fmt.Errorf("command identity is incomplete")
	}
	if !json.Valid(command.Payload) {
		return fmt.Errorf("command payload is invalid")
	}
	return nil
}

func validateSameOrigin(req *http.Request) error {
	origin := req.Header.Get("Origin")
	if origin == "" {
		return fmt.Errorf("missing origin")
	}
	parsed, err := url.Parse(origin)
	if err != nil {
		return err
	}
	if !strings.EqualFold(parsed.Host, req.Host) {
		return fmt.Errorf("origin host mismatch")
	}
	if parsed.Scheme != "http" && parsed.Scheme != "https" {
		return fmt.Errorf("origin scheme rejected")
	}
	return nil
}

func validateDoubleSubmitCSRF(req *http.Request) error {
	cookie, err := req.Cookie("cadence_csrf")
	if err != nil {
		return err
	}
	header := req.Header.Get("X-Cadence-CSRF")
	if header == "" || len(header) != len(cookie.Value) {
		return fmt.Errorf("csrf token missing")
	}
	if subtle.ConstantTimeCompare([]byte(header), []byte(cookie.Value)) != 1 {
		return fmt.Errorf("csrf token mismatch")
	}
	return nil
}

func writeCommandResponse(w http.ResponseWriter, encoded []byte) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.WriteHeader(http.StatusOK)
	_, _ = w.Write(encoded)
}
