// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.15.0

// Package quicken renders web pages as a fast shell plus deferred regions.
//
// A page paints its shell and lightweight skeletons immediately, then fills
// each region with its real content as that content becomes ready. Serve
// streams the universal floor over one HTTP response and stays readable with
// JavaScript disabled; a cadence.Policy decides, per region, whether the
// client reveals that content eagerly, on load, on visibility, or on hover.
// A page may also carry live regions, which Serve keeps live over a WebSocket
// (falling back to HTTP long-poll), pushing fine-grained patches as their
// server-held state changes.
//
// A page's shell can be authored as a Go function over a Frame (the
// func-registry style), as an HTML marker document parsed by FromMarkup, or
// as an html/template rendered with the funcs from Helpers and then passed to
// FromMarkup. All three styles produce the same Page, so Serve serves them
// identically regardless of how the shell was written.
//
// Two limitations apply to live regions in this release. The
// built-in session store keeps every session in memory and never evicts one,
// so each page load adds a session that lives for the process lifetime;
// supply a bounded SessionStore for production use via
// Serve(mux, path, p, pol, WithSessionStore(store)). The WebSocket upgrade
// performs no same-origin (Origin header) check, so an application that needs
// cross-site request protection should validate the Origin itself. Driving a
// live region still requires the unguessable per-session resume token
// embedded in the page.
package quicken
