// Code generated by goplus from helpers.gp. DO NOT EDIT.
//goplus:v v0.15.0

package quicken

import (
	"html/template"
	"strings"
)

// Helpers returns template funcs for authoring a quicken page as an
// html/template: lazy and live emit a region marker for the given id, and
// quickenHead emits the shim marker. Render the template with RenderMarkup and
// pass the result to FromMarkup. lazy and live panic on an invalid id, which is
// always a programming error.
func Helpers() template.FuncMap {
	return template.FuncMap{
		"lazy":        func(id string) template.HTML { return marker("lazy", id) },
		"live":        func(id string) template.HTML { return marker("live", id) },
		"quickenHead": func() template.HTML { return template.HTML("<!--quicken head-->") },
	}
}

func marker(kind, id string) template.HTML {
	if !validID(id) {
		panic("quicken: invalid region id " + id)
	}
	return template.HTML("<!--quicken " + kind + " " + id + "-->")
}

// RenderMarkup executes a template into a string, ready for FromMarkup.
func RenderMarkup(t *template.Template, data any) (string, error) {
	var b strings.Builder
	if err := t.Execute(&b, data); err != nil {
		return "", err
	}
	return b.String(), nil
}
