// Code generated by goplus from livewire.gp. DO NOT EDIT.
//goplus:v v0.15.0

package quicken

import (
	"encoding/json"
	"errors"
	"strconv"
	"strings"
)

// ClientMessage is the decoded client protocol. Resume and Event carry only
// the fields valid for that operation; an impossible hybrid cannot enter the
// runtime.
//
//goplus:enum ClientMessage
//goplus:derive off
type ClientMessage interface{ isClientMessage() }

//goplus:variant (ClientMessage) ResumeMessage(token string)
type ResumeMessage struct {
	Token string
}

func (ResumeMessage) isClientMessage() {}

//goplus:variant (ClientMessage) EventMessage(region string, event string, payload Payload, token string)
type EventMessage struct {
	Region  string
	Event   string
	Payload Payload
	Token   string
}

func (EventMessage) isClientMessage() {}

// ServerMessage is the server protocol. Each alternative owns exactly its
// valid payload, replacing the former struct with a string discriminator and
// seven conditionally meaningful fields.
//
//goplus:enum ServerMessage
//goplus:derive off
type ServerMessage interface{ isServerMessage() }

//goplus:variant (ServerMessage) FirstMessage(region string, tree Tree)
type FirstMessage struct {
	Region string
	Tree   Tree
}

func (FirstMessage) isServerMessage() {}

//goplus:variant (ServerMessage) FullMessage(region string, tree Tree)
type FullMessage struct {
	Region string
	Tree   Tree
}

func (FullMessage) isServerMessage() {}

//goplus:variant (ServerMessage) PatchMessage(region string, changed map[int]string)
type PatchMessage struct {
	Region  string
	Changed map[int]string
}

func (PatchMessage) isServerMessage() {}

//goplus:variant (ServerMessage) ErrorMessage(region string, message string)
type ErrorMessage struct {
	Region  string
	Message string
}

func (ErrorMessage) isServerMessage() {}

// clientMsg and serverMsg are deliberately confined JSON boundary DTOs.
// They are never queued or interpreted as domain values.
type clientMsg struct {
	Type    string  `json:"type"`
	Region  string  `json:"region,omitempty"`
	Event   string  `json:"event,omitempty"`
	Payload Payload `json:"payload,omitempty"`
	Token   string  `json:"token,omitempty"`
}

type serverMsg struct {
	Type     string         `json:"type"`
	Region   string         `json:"region"`
	Statics  []string       `json:"statics,omitempty"`
	Dynamics []string       `json:"dynamics,omitempty"`
	Changed  map[int]string `json:"changed,omitempty"`
	Message  string         `json:"message,omitempty"`
}

func decodeClient(b []byte) (ClientMessage, error) {
	var m clientMsg
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, err
	}
	switch m.Type {
	case "resume":
		if m.Token == "" {
			return nil, errors.New("quicken: resume needs token")
		}
		return ResumeMessage{Token: m.Token}, nil
	case "event":
		if m.Region == "" || m.Event == "" {
			return nil, errors.New("quicken: event needs region and event")
		}
		return EventMessage{Region: m.Region, Event: m.Event, Payload: m.Payload, Token: m.Token}, nil
	default:
		return nil, errors.New("quicken: unknown client message type")
	}
}

func encodeServer(m ServerMessage) ([]byte, error) {
	var wire serverMsg
	switch __gp_m0 := any(m).(type) {
	case FirstMessage:
		region := __gp_m0.Region
		tree := __gp_m0.Tree
		wire = serverMsg{Type: "first", Region: region, Statics: tree.Statics(), Dynamics: tree.Dynamics()}
	case FullMessage:
		region := __gp_m0.Region
		tree := __gp_m0.Tree
		wire = serverMsg{Type: "full", Region: region, Statics: tree.Statics(), Dynamics: tree.Dynamics()}
	case PatchMessage:
		region := __gp_m0.Region
		changed := __gp_m0.Changed
		wire = serverMsg{Type: "patch", Region: region, Changed: changed}
	case ErrorMessage:
		region := __gp_m0.Region
		message := __gp_m0.Message
		wire = serverMsg{Type: "error", Region: region, Message: message}
	default:
		panic("goplus: impossible enum value in match")
	}
	return json.Marshal(wire)
}

func firstMsg(region string, t Tree) ServerMessage { return FirstMessage{Region: region, Tree: t} }
func fullMsg(region string, t Tree) ServerMessage  { return FullMessage{Region: region, Tree: t} }
func patchMsg(region string, changed map[int]string) ServerMessage {
	return PatchMessage{Region: region, Changed: changed}
}
func errorMsg(region, message string) ServerMessage {
	return ErrorMessage{Region: region, Message: message}
}

// renderLiveHTML stitches a Tree, wrapping each dynamic slot in a marker
// element the client can address by index when applying a patch.
func renderLiveHTML(t Tree) string {
	statics := t.Statics()
	dynamics := t.Dynamics()
	if len(dynamics) == 0 {
		if len(statics) == 0 {
			return ""
		}
		return statics[0]
	}
	var b strings.Builder
	for i, d := range dynamics {
		b.WriteString(statics[i])
		b.WriteString(`<q-d data-qi="`)
		b.WriteString(strconv.Itoa(i))
		b.WriteString(`">`)
		b.WriteString(d)
		b.WriteString(`</q-d>`)
	}
	b.WriteString(statics[len(statics)-1])
	return b.String()
}
