// Code generated by goplus from page.gp. DO NOT EDIT.
//goplus:v v0.15.0

package quicken

import (
	"html/template"
	"strings"

	"goforge.dev/cadence"
)

// Shell renders the full HTML document for a page. It places each region's
// skeleton with f.Slot(id) and includes the shim with f.Head(). It returns a
// complete document; the transport streams region fills in just before the
// closing body tag.
type Shell func(f *Frame) template.HTML

// PageRegion is one registered page capability. StaticRegion can render a
// floor value; StatefulRegion additionally mounts resumable state.
//
//goplus:enum PageRegion
type PageRegion interface{ isPageRegion() }

//goplus:variant (PageRegion) StaticRegion(region Region)
type StaticRegion struct {
	Region Region
}

func (StaticRegion) isPageRegion() {}

//goplus:variant (PageRegion) StatefulRegion(region LiveRegion)
type StatefulRegion struct {
	Region LiveRegion
}

func (StatefulRegion) isPageRegion() {}

// PageRegionCases selects one handler per PageRegion variant for Fold.
type PageRegionCases[R any] struct {
	StaticRegion   func(region Region) R
	StatefulRegion func(region LiveRegion) R
}

// Fold reduces PageRegion by one-level case analysis.
func Fold[R any](p PageRegion, cs PageRegionCases[R]) R {
	switch m := any(p).(type) {
	case StaticRegion:
		return cs.StaticRegion(m.Region)
	case StatefulRegion:
		return cs.StatefulRegion(m.Region)
	default:
		panic("goplus: impossible enum value in Fold")
	}
}

// PageRegionEqOverrides carries optional per-variant hooks for PageRegionEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PageRegionEqOverrides struct {
	StaticRegion   func(x, y StaticRegion) (eq, handled bool)
	StatefulRegion func(x, y StatefulRegion) (eq, handled bool)
}

// PageRegionEqualWith reports structural equality of a and b under ov.
func PageRegionEqualWith(a, b PageRegion, ov PageRegionEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case StaticRegion:
		y, ok := any(b).(StaticRegion)
		if !ok {
			return false
		}
		if ov.StaticRegion != nil {
			if eq, handled := ov.StaticRegion(x, y); handled {
				return eq
			}
		}
		if x.Region != y.Region {
			return false
		}
		return true
	case StatefulRegion:
		y, ok := any(b).(StatefulRegion)
		if !ok {
			return false
		}
		if ov.StatefulRegion != nil {
			if eq, handled := ov.StatefulRegion(x, y); handled {
				return eq
			}
		}
		if x.Region != y.Region {
			return false
		}
		return true
	}
	return false
}

// PageRegionEqual reports structural equality of a and b.
func PageRegionEqual(a, b PageRegion) bool {
	return PageRegionEqualWith(a, b, PageRegionEqOverrides{})
}

// Page is a lazy page: a shell plus one ordered registry of region sums.
type Page struct {
	name    string
	shell   Shell
	regions map[string]PageRegion
	order   []string
}

// NewPage creates a page with the given shell.
func NewPage(shell Shell) *Page {
	return &Page{shell: shell, regions: map[string]PageRegion{}}
}

// Named sets the page's name, used to namespace its live endpoints (the
// WebSocket, poll, and event routes). The name must be empty or of the form
// [A-Za-z0-9_-]+; an invalid name panics. Returns the page for chaining.
func (p *Page) Named(name string) *Page {
	if name != "" && !validID(name) {
		panic("quicken: invalid page name " + name)
	}
	p.name = name
	return p
}

// Add registers a region. Regions render in the order added. Adding a region
// whose id is a duplicate or is not of the form [A-Za-z0-9_-]+ panics, which
// is always a programming error.
func (p *Page) Add(r Region) *Page {
	id := r.ID()
	if !validID(id) {
		panic("quicken: invalid region id " + id)
	}
	if _, ok := p.regions[id]; ok {
		panic("quicken: duplicate region id " + id)
	}
	p.regions[id] = StaticRegion{Region: r}
	p.order = append(p.order, id)
	return p
}

// AddLive registers a live region. Live regions render in the order added. A
// duplicate id (in either the deferred or live set) or an id not of the form
// [A-Za-z0-9_-]+ panics, which is always a programming error.
func (p *Page) AddLive(r LiveRegion) *Page {
	id := r.ID()
	if !validID(id) {
		panic("quicken: invalid region id " + id)
	}
	if _, ok := p.regions[id]; ok {
		panic("quicken: duplicate region id " + id)
	}
	p.regions[id] = StatefulRegion{Region: r}
	p.order = append(p.order, id)
	return p
}

func (p *Page) liveRegions() []LiveRegion {
	var out []LiveRegion
	for _, id := range p.order {
		switch __gp_m0 := any(p.regions[id]).(type) {
		case StatefulRegion:
			r := __gp_m0.Region
			out = append(out, r)
		case StaticRegion:
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return out
}

func (p *Page) liveIDs() []string {
	ids := make([]string, 0, len(p.order))
	for _, id := range p.order {
		switch any(p.regions[id]).(type) {
		case StatefulRegion:
			ids = append(ids, id)
		case StaticRegion:
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return ids
}

func (p *Page) staticIDs() []string {
	ids := make([]string, 0, len(p.order))
	for _, id := range p.order {
		switch any(p.regions[id]).(type) {
		case StaticRegion:
			ids = append(ids, id)
		case StatefulRegion:
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	return ids
}

func (p *Page) staticRegion(id string) (Region, bool) {
	entry, ok := p.regions[id]
	if !ok {
		return nil, false
	}
	switch __gp_m3 := any(entry).(type) {
	case StaticRegion:
		r := __gp_m3.Region
		return r, true
	case StatefulRegion:
		return nil, false
	default:
		panic("goplus: impossible enum value in match")
	}
	return nil, false
}

func (p *Page) liveRegion(id string) (LiveRegion, bool) {
	entry, ok := p.regions[id]
	if !ok {
		return nil, false
	}
	switch __gp_m4 := any(entry).(type) {
	case StatefulRegion:
		r := __gp_m4.Region
		return r, true
	case StaticRegion:
		return nil, false
	default:
		panic("goplus: impossible enum value in match")
	}
	return nil, false
}

func (p *Page) regionKind(id string) cadence.RegionKind {
	switch any(p.regions[id]).(type) {
	case StatefulRegion:
		return cadence.Stateful{}
	case StaticRegion:
		return cadence.Plain{}
	default:
		panic("goplus: impossible enum value in match")
	}
	return cadence.Plain{}
}

// Frame is handed to a Shell so it can place region skeletons and the shim.
type Frame struct {
	page *Page
	ctx  RenderContext
}

// Head returns the markup for the document head: the shim script tag.
func (f *Frame) Head() template.HTML {
	return template.HTML(`<script src="` + ScriptPath + `"></script>`)
}

// Slot returns the placeholder for the region with the given id: a slot
// element carrying the region's skeleton, which the transport later fills.
func (f *Frame) Slot(id string) template.HTML {
	if entry, ok := f.page.regions[id]; ok {
		switch __gp_m6 := any(entry).(type) {
		case StaticRegion:
			r := __gp_m6.Region
			sk := r.Skeleton(f.ctx).HTML()
			return template.HTML(`<div id="q-slot-` + id + `" data-q-slot data-q-pending>` + sk + `</div>`)
		case StatefulRegion:
			r := __gp_m6.Region
			sk := r.Skeleton(f.ctx).HTML()
			return template.HTML(`<div id="q-slot-` + id + `" data-q-slot data-q-live data-q-pending>` + sk + `</div>`)
		default:
			panic("goplus: impossible enum value in match")
		}
	}
	esc := template.HTMLEscapeString(id)
	return template.HTML(`<div id="q-slot-` + esc + `" data-q-slot data-q-missing></div>`)
}

// splitBody splits a complete document at the last closing body tag so the
// transport can stream fills between the body content and the closing tags.
// With no closing body tag the whole document is head and the tail is empty.
func splitBody(doc string) (head, tail string) {
	i := strings.LastIndex(doc, "</body>")
	if i < 0 {
		return doc, ""
	}
	return doc[:i], doc[i:]
}

func validID(id string) bool {
	if id == "" {
		return false
	}
	for _, c := range id {
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9', c == '_', c == '-':
		default:
			return false
		}
	}
	return true
}
