// Code generated by goplus from program.gp. DO NOT EDIT.
//goplus:v v0.28.0

package quicken

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"html"
	"net/http"
	"strings"

	"goforge.dev/cadence"
	teaprogram "goforge.dev/cadence/program"
	browser "goforge.dev/quicken/web/browser"
)

// BrowserAssets are immutable, content-addressed browser runtime assets.
type BrowserAssets struct {
	Hash        string
	WasmURL     string
	WasmExecURL string
	LoaderURL   string
}

func (a BrowserAssets) Validate() error {
	if a.Hash == "" || a.WasmURL == "" || a.WasmExecURL == "" || a.LoaderURL == "" {
		return fmt.Errorf("quicken: browser asset hash and URLs must be non-empty")
	}
	return nil
}

// Program is the isomorphic definition compiled into the server and browser
// targets. Bootstrap contains public state only.
type Program[Bootstrap any, Model any, Msg any] struct {
	AppID           string
	ID              string
	Plan            cadence.ValidatedPlan
	Assets          BrowserAssets
	CommandEndpoint string
	SocketEndpoint  string
	PollEndpoint    string
	EventEndpoint   string
	DocumentTitle   string
	Bootstrap       func(*http.Request) (Bootstrap, error)
	Logic           func(Bootstrap) teaprogram.Logic[Model, Msg]
	View            teaprogram.View[Model, Msg, browser.Node[Msg]]
	Skeleton        func(Bootstrap) browser.Node[Msg]
	NoScript        func(Bootstrap) browser.Node[Msg]
	InstanceID      func(*http.Request) (string, error)
	ResumeToken     func(*http.Request) string
	InitialRevision func(*http.Request) uint64
}

type ProgramRegion[Bootstrap any, Model any, Msg any] struct {
	MountID string
	Program Program[Bootstrap, Model, Msg]
}

type FullPageProgram[Bootstrap any, Model any, Msg any] struct {
	MountID string
	Program Program[Bootstrap, Model, Msg]
}

// ProgramRender separates composable fragments from the complete response.
type ProgramRender struct {
	HTML         string
	NoScriptHTML string
	ManifestTag  string
	AssetTags    string
	Document     string
}

func (r ProgramRegion[Bootstrap, Model, Msg]) Render(req *http.Request) (ProgramRender, error) {
	return renderProgram(req, r.MountID, browser.ScopeIsland, r.Program)
}

func (r ProgramRegion[Bootstrap, Model, Msg]) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	rendered, err := r.Render(req)
	if err != nil {
		http.Error(w, "program render failed", http.StatusInternalServerError)
		return
	}
	writeProgramHeaders(w)
	_, _ = w.Write([]byte(
		rendered.HTML + rendered.NoScriptHTML + rendered.ManifestTag + rendered.AssetTags,
	))
}

func (p FullPageProgram[Bootstrap, Model, Msg]) Render(req *http.Request) (ProgramRender, error) {
	return renderProgram(req, p.MountID, browser.ScopeFullPage, p.Program)
}

func (p FullPageProgram[Bootstrap, Model, Msg]) ServeHTTP(w http.ResponseWriter, req *http.Request) {
	rendered, err := p.Render(req)
	if err != nil {
		http.Error(w, "program render failed", http.StatusInternalServerError)
		return
	}
	writeProgramHeaders(w)
	_, _ = w.Write([]byte(rendered.Document))
}

func renderProgram[Bootstrap any, Model any, Msg any](
	req *http.Request,
	mountID, scope string,
	definition Program[Bootstrap, Model, Msg],
) (ProgramRender, error) {
	if err := validateProgram(mountID, definition); err != nil {
		return ProgramRender{}, err
	}
	bootstrap, err := definition.Bootstrap(req)
	if err != nil {
		return ProgramRender{}, err
	}
	logic := definition.Logic(bootstrap)
	if logic.Init == nil || logic.Update == nil || definition.View == nil {
		return ProgramRender{}, fmt.Errorf("quicken: program logic and view must be non-nil")
	}
	initial := logic.Init()
	planWire := browser.PlanToWire(definition.Plan.Plan())
	var node browser.Node[Msg]
	switch planWire.Initial {
	case "full":
		node = definition.View(initial.Model)
	case "skeleton":
		if definition.Skeleton == nil {
			return ProgramRender{}, fmt.Errorf("quicken: skeleton plan requires Program.Skeleton")
		}
		node = definition.Skeleton(bootstrap)
	case "none":
		node = browser.Element[Msg]("div")
	default:
		return ProgramRender{}, fmt.Errorf("quicken: unknown initial render %q", planWire.Initial)
	}
	renderedHTML, err := browser.RenderHTML(node, browser.RenderOptions{
		ProgramID: definition.ID,
		MountID:   mountID,
	})
	if err != nil {
		return ProgramRender{}, err
	}
	noScriptHTML := ""
	if definition.NoScript != nil {
		fallback, err := browser.RenderHTML(definition.NoScript(bootstrap), browser.RenderOptions{})
		if err != nil {
			return ProgramRender{}, err
		}
		noScriptHTML = "<noscript>" + fallback + "</noscript>"
	} else if planWire.Fallback == "requires-client" {
		return ProgramRender{}, fmt.Errorf("quicken: RequiresClient plans must provide Program.NoScript")
	}

	bootstrapJSON, err := json.Marshal(bootstrap)
	if err != nil {
		return ProgramRender{}, err
	}
	instanceID, err := programInstanceID(req, definition)
	if err != nil {
		return ProgramRender{}, err
	}
	manifest := browser.NewManifest(
		definition.Assets.Hash, definition.AppID, definition.ID,
		instanceID, mountID, scope, definition.Plan, bootstrapJSON,
	)
	manifest.Endpoints = browser.Endpoints{
		Command:  definition.CommandEndpoint,
		Socket:   definition.SocketEndpoint,
		LongPoll: definition.PollEndpoint,
		Event:    definition.EventEndpoint,
	}
	if definition.ResumeToken != nil {
		manifest.ResumeToken = definition.ResumeToken(req)
	}
	if definition.InitialRevision != nil {
		manifest.InitialRevision = definition.InitialRevision(req)
	}
	encodedManifest, err := manifest.Encode()
	if err != nil {
		return ProgramRender{}, err
	}
	manifestTag := `<script type="application/json" data-cadence-manifest>` +
		string(encodedManifest) + `</script>`
	assetTags := renderAssetTags(definition.Assets)
	title := html.EscapeString(definition.DocumentTitle)
	document := "<!doctype html><html><head><meta charset=\"utf-8\">" +
		"<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">" +
		"<title>" + title + "</title></head><body>" +
		renderedHTML + noScriptHTML + manifestTag + assetTags +
		"</body></html>"
	return ProgramRender{
		HTML: renderedHTML, NoScriptHTML: noScriptHTML,
		ManifestTag: manifestTag, AssetTags: assetTags, Document: document,
	}, nil
}

func validateProgram[Bootstrap any, Model any, Msg any](
	mountID string,
	definition Program[Bootstrap, Model, Msg],
) error {
	if mountID == "" || definition.AppID == "" || definition.ID == "" {
		return fmt.Errorf("quicken: mount, app, and program IDs must be non-empty")
	}
	if definition.Bootstrap == nil || definition.Logic == nil {
		return fmt.Errorf("quicken: bootstrap and logic factories must be non-nil")
	}
	return definition.Assets.Validate()
}

func programInstanceID[Bootstrap any, Model any, Msg any](
	req *http.Request,
	definition Program[Bootstrap, Model, Msg],
) (string, error) {
	if definition.InstanceID != nil {
		return definition.InstanceID(req)
	}
	var bytes [16]byte
	if _, err := rand.Read(bytes[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(bytes[:]), nil
}

func renderAssetTags(assets BrowserAssets) string {
	return `<script defer src="` + html.EscapeString(assets.WasmExecURL) + `"></script>` +
		`<script defer src="` + html.EscapeString(assets.LoaderURL) +
		`" data-wasm="` + html.EscapeString(assets.WasmURL) + `"></script>`
}

func writeProgramHeaders(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("X-Content-Type-Options", "nosniff")
	w.Header().Set(
		"Content-Security-Policy",
		"default-src 'self'; script-src 'self' 'wasm-unsafe-eval'; connect-src 'self' ws: wss:; object-src 'none'; base-uri 'self'",
	)
	w.Header().Set("Referrer-Policy", "same-origin")
}

func escapeScriptJSON(data []byte) string {
	value := string(data)
	value = strings.ReplaceAll(value, "<", `\u003c`)
	value = strings.ReplaceAll(value, ">", `\u003e`)
	value = strings.ReplaceAll(value, "&", `\u0026`)
	return value
}
