// Code generated by goplus from renderresult.gp. DO NOT EDIT.
//goplus:v v0.15.0

package quicken

import (
	"fmt"

	"goforge.dev/goplus/std/result"
)

// RenderFailure makes mount errors and recovered render panics explicit.
//
//goplus:enum RenderFailure
//goplus:derive off
type RenderFailure interface{ isRenderFailure() }

//goplus:variant (RenderFailure) MountFailed(err error)
type MountFailed struct {
	Err error
}

func (MountFailed) isRenderFailure() {}

//goplus:variant (RenderFailure) RenderPanicked
type RenderPanicked struct{}

func (RenderPanicked) isRenderFailure() {}

//goplus:method (RenderFailure) Error
func Error(f RenderFailure) string {
	switch __gp_m0 := any(f).(type) {
	case MountFailed:
		err := __gp_m0.Err
		return fmt.Sprintf("mount failed: %v", err)
	case RenderPanicked:
		return "render panicked"
	default:
		panic("goplus: impossible enum value in match")
	}
	return "render failed"
}

type mountedRegion struct {
	tree  Tree
	state State
}

func renderLiveFirst(lr LiveRegion, ctx RenderContext) (out result.Result[mountedRegion, RenderFailure]) {
	defer func() {
		if recover() != nil {
			out = result.Err[mountedRegion, RenderFailure]{Err: RenderPanicked{}}
		}
	}()
	s, err := lr.Mount(ctx, nil)
	if err != nil {
		return result.Err[mountedRegion, RenderFailure]{Err: MountFailed{Err: err}}
	}
	return result.Ok[mountedRegion, RenderFailure]{Value: mountedRegion{tree: lr.Render(s), state: s}}
}

func safeRender(lr LiveRegion, s State) (out result.Result[Tree, RenderFailure]) {
	defer func() {
		if recover() != nil {
			out = result.Err[Tree, RenderFailure]{Err: RenderPanicked{}}
		}
	}()
	return result.Ok[Tree, RenderFailure]{Value: lr.Render(s)}
}
