// Code generated by goplus from session.gp. DO NOT EDIT.
//goplus:v v0.15.0

package quicken

import (
	"crypto/rand"
	"encoding/hex"
	"sync"
)

// regionState is a live region's memory on one connection: its opaque State
// and the statics and dynamic slot values last sent to the client, which the
// diff compares against. Both must be kept together: a render can change
// static content at the same dynamic-slot count (for example a class toggle
// on an otherwise unchanged element), and diffing only the dynamics would
// miss that change and leave the client with stale statics forever.
type regionState struct {
	state        State
	lastStatics  []string
	lastDynamics []string
}

// LiveSession holds one connection's per-region state, keyed by region id.
type LiveSession struct {
	mu        sync.Mutex
	regions   map[string]*regionState
	outbox    chan ServerMessage
	firstSent bool
}

// markFirstSent reports true the first time it is called on a session, and
// false on every call after that. The long-poll path uses it to enqueue the
// "first" messages for all regions exactly once, on the poll that resumes
// the session.
func (s *LiveSession) markFirstSent() bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	if s.firstSent {
		return false
	}
	s.firstSent = true
	return true
}

func (s *LiveSession) get(id string) (*regionState, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	rs, ok := s.regions[id]
	return rs, ok
}

func (s *LiveSession) set(id string, rs *regionState) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.regions[id] = rs
}

// withRegion runs fn against the region's state while holding the session
// lock, so a full read-modify-write of the regionState is atomic. It returns
// false when the region id is not present.
func (s *LiveSession) withRegion(id string, fn func(*regionState)) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	rs, ok := s.regions[id]
	if !ok {
		return false
	}
	fn(rs)
	return true
}

// SessionStore maps a resume token to a LiveSession. The in-memory
// implementation is the only one built for v1; the interface lets a shared
// store replace it later without touching the core.
type SessionStore interface {
	Get(token string) (*LiveSession, bool)
	Put(token string, s *LiveSession)
	Delete(token string)
}

type memoryStore struct {
	mu sync.RWMutex
	m  map[string]*LiveSession
}

// NewMemoryStore returns an in-process SessionStore.
func NewMemoryStore() SessionStore {
	return &memoryStore{m: map[string]*LiveSession{}}
}

func (s *memoryStore) Get(token string) (*LiveSession, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	sess, ok := s.m[token]
	return sess, ok
}

func (s *memoryStore) Put(token string, sess *LiveSession) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.m[token] = sess
}

func (s *memoryStore) Delete(token string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	delete(s.m, token)
}

// newToken mints an opaque resume token: 16 random bytes as hex.
func newToken() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	return hex.EncodeToString(b[:]), nil
}
