// Code generated by goplus from app.gp. DO NOT EDIT.
//goplus:v v0.28.0

package mobile

import (
	"gioui.org/app"
	"gioui.org/layout"
	"gioui.org/widget/material"
	"goforge.dev/cadence/program"
	native "goforge.dev/quicken/native"
)

type View[Model, Msg any] func(layout.Context, Model, *native.UI[Msg], Environment) layout.Dimensions

type Application[Model, Msg any] struct {
	ID          string
	Logic       program.Logic[Model, Msg]
	View        View[Model, Msg]
	Environment func() Environment
	Effects     native.EffectHandler[Msg]
	Theme       *material.Theme
}

func Run[Model, Msg any](application Application[Model, Msg]) (Model, error) {
	app.ID = application.ID
	environment := application.Environment
	if environment == nil {
		environment = func() Environment {
			return Environment{
				Platform:  CurrentPlatform(),
				Lifecycle: LifecycleForeground{},
			}
		}
	}
	view := func(gtx layout.Context, model Model, ui *native.UI[Msg]) layout.Dimensions {
		return application.View(gtx, model, ui, environment())
	}
	window := native.NewWindow(native.WindowOptions{})
	type result struct {
		model Model
		err   error
	}
	done := make(chan result, 1)
	go func() {
		model, err := native.RunWindow(
			window,
			application.Logic,
			view,
			application.Effects,
			application.Theme,
		)
		done <- result{model: model, err: err}
	}()
	native.Main()
	out := <-done
	return out.model, out.err
}
