// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package mobile runs Cadence programs as native iOS and Android applications
// through Quicken Native and Gio.
package mobile
