// Code generated by goplus from platform.gp. DO NOT EDIT.
//goplus:v v0.28.0

package mobile

//goplus:enum Platform
type Platform interface{ isPlatform() }

//goplus:variant (Platform) PlatformUnknown
type PlatformUnknown struct{}

func (PlatformUnknown) isPlatform() {}

//goplus:variant (Platform) PlatformIOS
type PlatformIOS struct{}

func (PlatformIOS) isPlatform() {}

//goplus:variant (Platform) PlatformAndroid
type PlatformAndroid struct{}

func (PlatformAndroid) isPlatform() {}

// PlatformCases selects one handler per Platform variant for PlatformFold.
type PlatformCases[R any] struct {
	PlatformUnknown func() R
	PlatformIOS     func() R
	PlatformAndroid func() R
}

// PlatformFold reduces Platform by one-level case analysis.
func PlatformFold[R any](p Platform, cs PlatformCases[R]) R {
	switch any(p).(type) {
	case PlatformUnknown:
		return cs.PlatformUnknown()
	case PlatformIOS:
		return cs.PlatformIOS()
	case PlatformAndroid:
		return cs.PlatformAndroid()
	default:
		panic("goplus: impossible enum value in PlatformFold")
	}
}

// PlatformEqOverrides carries optional per-variant hooks for PlatformEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PlatformEqOverrides struct {
	PlatformUnknown func(x, y PlatformUnknown) (eq, handled bool)
	PlatformIOS     func(x, y PlatformIOS) (eq, handled bool)
	PlatformAndroid func(x, y PlatformAndroid) (eq, handled bool)
}

// PlatformEqualWith reports structural equality of a and b under ov.
func PlatformEqualWith(a, b Platform, ov PlatformEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case PlatformUnknown:
		y, ok := any(b).(PlatformUnknown)
		if !ok {
			return false
		}
		if ov.PlatformUnknown != nil {
			if eq, handled := ov.PlatformUnknown(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PlatformIOS:
		y, ok := any(b).(PlatformIOS)
		if !ok {
			return false
		}
		if ov.PlatformIOS != nil {
			if eq, handled := ov.PlatformIOS(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PlatformAndroid:
		y, ok := any(b).(PlatformAndroid)
		if !ok {
			return false
		}
		if ov.PlatformAndroid != nil {
			if eq, handled := ov.PlatformAndroid(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// PlatformEqual reports structural equality of a and b.
func PlatformEqual(a, b Platform) bool {
	return PlatformEqualWith(a, b, PlatformEqOverrides{})
}

//goplus:enum Lifecycle
type Lifecycle interface{ isLifecycle() }

//goplus:variant (Lifecycle) LifecycleForeground
type LifecycleForeground struct{}

func (LifecycleForeground) isLifecycle() {}

//goplus:variant (Lifecycle) LifecycleBackground
type LifecycleBackground struct{}

func (LifecycleBackground) isLifecycle() {}

//goplus:variant (Lifecycle) LifecycleInactive
type LifecycleInactive struct{}

func (LifecycleInactive) isLifecycle() {}

// LifecycleCases selects one handler per Lifecycle variant for LifecycleFold.
type LifecycleCases[R any] struct {
	LifecycleForeground func() R
	LifecycleBackground func() R
	LifecycleInactive   func() R
}

// LifecycleFold reduces Lifecycle by one-level case analysis.
func LifecycleFold[R any](l Lifecycle, cs LifecycleCases[R]) R {
	switch any(l).(type) {
	case LifecycleForeground:
		return cs.LifecycleForeground()
	case LifecycleBackground:
		return cs.LifecycleBackground()
	case LifecycleInactive:
		return cs.LifecycleInactive()
	default:
		panic("goplus: impossible enum value in LifecycleFold")
	}
}

// LifecycleEqOverrides carries optional per-variant hooks for LifecycleEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type LifecycleEqOverrides struct {
	LifecycleForeground func(x, y LifecycleForeground) (eq, handled bool)
	LifecycleBackground func(x, y LifecycleBackground) (eq, handled bool)
	LifecycleInactive   func(x, y LifecycleInactive) (eq, handled bool)
}

// LifecycleEqualWith reports structural equality of a and b under ov.
func LifecycleEqualWith(a, b Lifecycle, ov LifecycleEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case LifecycleForeground:
		y, ok := any(b).(LifecycleForeground)
		if !ok {
			return false
		}
		if ov.LifecycleForeground != nil {
			if eq, handled := ov.LifecycleForeground(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LifecycleBackground:
		y, ok := any(b).(LifecycleBackground)
		if !ok {
			return false
		}
		if ov.LifecycleBackground != nil {
			if eq, handled := ov.LifecycleBackground(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case LifecycleInactive:
		y, ok := any(b).(LifecycleInactive)
		if !ok {
			return false
		}
		if ov.LifecycleInactive != nil {
			if eq, handled := ov.LifecycleInactive(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// LifecycleEqual reports structural equality of a and b.
func LifecycleEqual(a, b Lifecycle) bool {
	return LifecycleEqualWith(a, b, LifecycleEqOverrides{})
}

//goplus:enum Permission
type Permission interface{ isPermission() }

//goplus:variant (Permission) PermissionCamera
type PermissionCamera struct{}

func (PermissionCamera) isPermission() {}

//goplus:variant (Permission) PermissionLocation
type PermissionLocation struct{}

func (PermissionLocation) isPermission() {}

//goplus:variant (Permission) PermissionMicrophone
type PermissionMicrophone struct{}

func (PermissionMicrophone) isPermission() {}

//goplus:variant (Permission) PermissionNotifications
type PermissionNotifications struct{}

func (PermissionNotifications) isPermission() {}

//goplus:variant (Permission) PermissionPhotos
type PermissionPhotos struct{}

func (PermissionPhotos) isPermission() {}

// PermissionCases selects one handler per Permission variant for PermissionFold.
type PermissionCases[R any] struct {
	PermissionCamera        func() R
	PermissionLocation      func() R
	PermissionMicrophone    func() R
	PermissionNotifications func() R
	PermissionPhotos        func() R
}

// PermissionFold reduces Permission by one-level case analysis.
func PermissionFold[R any](p Permission, cs PermissionCases[R]) R {
	switch any(p).(type) {
	case PermissionCamera:
		return cs.PermissionCamera()
	case PermissionLocation:
		return cs.PermissionLocation()
	case PermissionMicrophone:
		return cs.PermissionMicrophone()
	case PermissionNotifications:
		return cs.PermissionNotifications()
	case PermissionPhotos:
		return cs.PermissionPhotos()
	default:
		panic("goplus: impossible enum value in PermissionFold")
	}
}

// PermissionEqOverrides carries optional per-variant hooks for PermissionEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type PermissionEqOverrides struct {
	PermissionCamera        func(x, y PermissionCamera) (eq, handled bool)
	PermissionLocation      func(x, y PermissionLocation) (eq, handled bool)
	PermissionMicrophone    func(x, y PermissionMicrophone) (eq, handled bool)
	PermissionNotifications func(x, y PermissionNotifications) (eq, handled bool)
	PermissionPhotos        func(x, y PermissionPhotos) (eq, handled bool)
}

// PermissionEqualWith reports structural equality of a and b under ov.
func PermissionEqualWith(a, b Permission, ov PermissionEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case PermissionCamera:
		y, ok := any(b).(PermissionCamera)
		if !ok {
			return false
		}
		if ov.PermissionCamera != nil {
			if eq, handled := ov.PermissionCamera(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PermissionLocation:
		y, ok := any(b).(PermissionLocation)
		if !ok {
			return false
		}
		if ov.PermissionLocation != nil {
			if eq, handled := ov.PermissionLocation(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PermissionMicrophone:
		y, ok := any(b).(PermissionMicrophone)
		if !ok {
			return false
		}
		if ov.PermissionMicrophone != nil {
			if eq, handled := ov.PermissionMicrophone(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PermissionNotifications:
		y, ok := any(b).(PermissionNotifications)
		if !ok {
			return false
		}
		if ov.PermissionNotifications != nil {
			if eq, handled := ov.PermissionNotifications(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case PermissionPhotos:
		y, ok := any(b).(PermissionPhotos)
		if !ok {
			return false
		}
		if ov.PermissionPhotos != nil {
			if eq, handled := ov.PermissionPhotos(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// PermissionEqual reports structural equality of a and b.
func PermissionEqual(a, b Permission) bool {
	return PermissionEqualWith(a, b, PermissionEqOverrides{})
}

type Insets struct {
	Top, Right, Bottom, Left float32
}

type Environment struct {
	Platform  Platform
	Lifecycle Lifecycle
	SafeArea  Insets
}

func CurrentPlatform() Platform { return platform() }

// Keep enum construction in the untagged unit where the Go+ generator can
// resolve the complete variant algebra.
func iosPlatform() Platform     { return PlatformIOS() }
func androidPlatform() Platform { return PlatformAndroid() }
