// Code generated by goplus from semantic.gp. DO NOT EDIT.
//goplus:v v0.28.0

package mobile

import (
	"gioui.org/layout"
	"gioui.org/unit"
	"goforge.dev/cadence/sel"
	native "goforge.dev/quicken/native"
)

// SELView interprets one semantic tree with mobile platform mechanics. iOS
// uses 44 dp controls, Android uses 48 dp controls, and both apply safe-area
// insets from the mobile environment.
func SELView[Model any, Msg any](
	render func(Model) sel.Element[Msg],
	palette native.Palette,
) View[Model, Msg] {
	return func(
		gtx layout.Context,
		model Model,
		ui *native.UI[Msg],
		environment Environment,
	) layout.Dimensions {
		idiom := native.AndroidIdiom()
		switch __gp_m0 := any(environment.Platform).(type) {
		case nil:
			//goplus:pattern PlatformIOS()
			idiom = native.IOSIdiom()
		case nil:
			//goplus:pattern PlatformAndroid()
			idiom = native.AndroidIdiom()
		case nil:
			//goplus:pattern PlatformUnknown()
			idiom = native.AndroidIdiom()
		}
		view := native.SELViewWithIdiom(render, palette, idiom)
		inset := layout.Inset{
			Top:    unit.Dp(environment.SafeArea.Top),
			Right:  unit.Dp(environment.SafeArea.Right),
			Bottom: unit.Dp(environment.SafeArea.Bottom),
			Left:   unit.Dp(environment.SafeArea.Left),
		}
		return inset.Layout(gtx, func(gtx layout.Context) layout.Dimensions {
			return view(gtx, model, ui)
		})
	}
}
