// Code generated by goplus from main.gp. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"log"

	"gioui.org/unit"
	taskboard "goforge.dev/cadence-taskboard"
	cadencegio "goforge.dev/quicken/native"
)

func main() {
	window := cadencegio.NewWindow(cadencegio.WindowOptions{
		Title:  "Cadence Task Board",
		Width:  unit.Dp(720),
		Height: unit.Dp(540),
	})
	go func() {
		_, err := cadencegio.RunWindow(
			window,
			taskboard.Logic(taskboard.InitialModel(), taskboard.LocalSave),
			cadencegio.SELView(taskboard.SemanticView, cadencegio.DefaultPalette()),
			nil,
			nil,
		)
		if err != nil {
			log.Print(err)
		}
	}()
	cadencegio.Main()
}
