// Code generated by goplus from derive-gen. DO NOT EDIT.
//goplus:v v0.28.0

package taskboard

import "pgregory.net/rapid"

// GenFilter draws a random Filter (derived by goplus).
func GenFilter(t *rapid.T) Filter {
	return genFilterDepth(t, 3)
}

func genFilterDepth(t *rapid.T, depth int) Filter {
	n := rapid.IntRange(0, 2).Draw(t, "variant")
	switch n {
	case 0:
		return FilterAll{}
	case 1:
		return FilterActive{}
	case 2:
		return FilterCompleted{}
	}
	panic("goplus: impossible variant index in GenFilter")
}

// GenMsg draws a random Msg (derived by goplus).
func GenMsg(t *rapid.T) Msg {
	return genMsgDepth(t, 3)
}

func genMsgDepth(t *rapid.T, depth int) Msg {
	n := rapid.IntRange(0, 6).Draw(t, "variant")
	if depth <= 0 {
		n = []int{0, 1, 2, 3, 5, 6}[rapid.IntRange(0, 5).Draw(t, "leaf")]
	}
	switch n {
	case 0:
		return DraftChanged{Value: rapid.String().Draw(t, "f")}
	case 1:
		return AddRequested{}
	case 2:
		return ToggleRequested{Id: rapid.Int().Draw(t, "f")}
	case 3:
		return DeleteRequested{Id: rapid.Int().Draw(t, "f")}
	case 4:
		return FilterRequested{Filter: genFilterDepth(t, depth-1)}
	case 5:
		return SaveSucceeded{Tasks: rapid.Make[[]Task]().Draw(t, "f")}
	case 6:
		return SaveFailed{Message: rapid.String().Draw(t, "f")}
	}
	panic("goplus: impossible variant index in GenMsg")
}
