// Code generated by goplus from model.gp. DO NOT EDIT.
//goplus:v v0.28.0

package taskboard

import (
	"encoding/json"
	"fmt"

	"goforge.dev/cadence/program"
)

type Task struct {
	ID    int    `json:"id"`
	Title string `json:"title"`
	Done  bool   `json:"done"`
}

//goplus:enum Filter
type Filter interface{ isFilter() }

//goplus:variant (Filter) FilterAll
type FilterAll struct{}

func (FilterAll) isFilter() {}

//goplus:variant (Filter) FilterActive
type FilterActive struct{}

func (FilterActive) isFilter() {}

//goplus:variant (Filter) FilterCompleted
type FilterCompleted struct{}

func (FilterCompleted) isFilter() {}

// FilterCases selects one handler per Filter variant for FilterFold.
type FilterCases[R any] struct {
	FilterAll       func() R
	FilterActive    func() R
	FilterCompleted func() R
}

// FilterFold reduces Filter by one-level case analysis.
func FilterFold[R any](f Filter, cs FilterCases[R]) R {
	switch any(f).(type) {
	case FilterAll:
		return cs.FilterAll()
	case FilterActive:
		return cs.FilterActive()
	case FilterCompleted:
		return cs.FilterCompleted()
	default:
		panic("goplus: impossible enum value in FilterFold")
	}
}

// FilterEqOverrides carries optional per-variant hooks for FilterEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type FilterEqOverrides struct {
	FilterAll       func(x, y FilterAll) (eq, handled bool)
	FilterActive    func(x, y FilterActive) (eq, handled bool)
	FilterCompleted func(x, y FilterCompleted) (eq, handled bool)
}

// FilterEqualWith reports structural equality of a and b under ov.
func FilterEqualWith(a, b Filter, ov FilterEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case FilterAll:
		y, ok := any(b).(FilterAll)
		if !ok {
			return false
		}
		if ov.FilterAll != nil {
			if eq, handled := ov.FilterAll(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FilterActive:
		y, ok := any(b).(FilterActive)
		if !ok {
			return false
		}
		if ov.FilterActive != nil {
			if eq, handled := ov.FilterActive(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case FilterCompleted:
		y, ok := any(b).(FilterCompleted)
		if !ok {
			return false
		}
		if ov.FilterCompleted != nil {
			if eq, handled := ov.FilterCompleted(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	}
	return false
}

// FilterEqual reports structural equality of a and b.
func FilterEqual(a, b Filter) bool {
	return FilterEqualWith(a, b, FilterEqOverrides{})
}

type Model struct {
	Tasks  []Task
	Draft  string
	Filter Filter
	Saving bool
	Error  string
	NextID int
}

//goplus:enum Msg
//goplus:derive gen
type Msg interface{ isMsg() }

//goplus:variant (Msg) DraftChanged(value string)
type DraftChanged struct {
	Value string
}

func (DraftChanged) isMsg() {}

//goplus:variant (Msg) AddRequested
type AddRequested struct{}

func (AddRequested) isMsg() {}

//goplus:variant (Msg) ToggleRequested(id int)
type ToggleRequested struct {
	Id int
}

func (ToggleRequested) isMsg() {}

//goplus:variant (Msg) DeleteRequested(id int)
type DeleteRequested struct {
	Id int
}

func (DeleteRequested) isMsg() {}

//goplus:variant (Msg) FilterRequested(filter Filter)
type FilterRequested struct {
	Filter Filter
}

func (FilterRequested) isMsg() {}

//goplus:variant (Msg) SaveSucceeded(tasks []Task)
type SaveSucceeded struct {
	Tasks []Task
}

func (SaveSucceeded) isMsg() {}

//goplus:variant (Msg) SaveFailed(message string)
type SaveFailed struct {
	Message string
}

func (SaveFailed) isMsg() {}

// MsgCases selects one handler per Msg variant for MsgFold.
type MsgCases[R any] struct {
	DraftChanged    func(value string) R
	AddRequested    func() R
	ToggleRequested func(id int) R
	DeleteRequested func(id int) R
	FilterRequested func(filter Filter) R
	SaveSucceeded   func(tasks []Task) R
	SaveFailed      func(message string) R
}

// MsgFold reduces Msg by one-level case analysis.
func MsgFold[R any](m Msg, cs MsgCases[R]) R {
	switch m := any(m).(type) {
	case DraftChanged:
		return cs.DraftChanged(m.Value)
	case AddRequested:
		return cs.AddRequested()
	case ToggleRequested:
		return cs.ToggleRequested(m.Id)
	case DeleteRequested:
		return cs.DeleteRequested(m.Id)
	case FilterRequested:
		return cs.FilterRequested(m.Filter)
	case SaveSucceeded:
		return cs.SaveSucceeded(m.Tasks)
	case SaveFailed:
		return cs.SaveFailed(m.Message)
	default:
		panic("goplus: impossible enum value in MsgFold")
	}
}

// MsgEqOverrides carries optional per-variant hooks for MsgEqualWith.
// A hook returning handled=false falls through to the derived comparison.
type MsgEqOverrides struct {
	DraftChanged    func(x, y DraftChanged) (eq, handled bool)
	AddRequested    func(x, y AddRequested) (eq, handled bool)
	ToggleRequested func(x, y ToggleRequested) (eq, handled bool)
	DeleteRequested func(x, y DeleteRequested) (eq, handled bool)
	FilterRequested func(x, y FilterRequested) (eq, handled bool)
	SaveSucceeded   func(x, y SaveSucceeded) (eq, handled bool)
	SaveFailed      func(x, y SaveFailed) (eq, handled bool)
}

// MsgEqualWith reports structural equality of a and b under ov.
func MsgEqualWith(a, b Msg, ov MsgEqOverrides) bool {
	if a == nil || b == nil {
		return a == nil && b == nil
	}
	switch x := any(a).(type) {
	case DraftChanged:
		y, ok := any(b).(DraftChanged)
		if !ok {
			return false
		}
		if ov.DraftChanged != nil {
			if eq, handled := ov.DraftChanged(x, y); handled {
				return eq
			}
		}
		if x.Value != y.Value {
			return false
		}
		return true
	case AddRequested:
		y, ok := any(b).(AddRequested)
		if !ok {
			return false
		}
		if ov.AddRequested != nil {
			if eq, handled := ov.AddRequested(x, y); handled {
				return eq
			}
		}
		_ = y
		return true
	case ToggleRequested:
		y, ok := any(b).(ToggleRequested)
		if !ok {
			return false
		}
		if ov.ToggleRequested != nil {
			if eq, handled := ov.ToggleRequested(x, y); handled {
				return eq
			}
		}
		if x.Id != y.Id {
			return false
		}
		return true
	case DeleteRequested:
		y, ok := any(b).(DeleteRequested)
		if !ok {
			return false
		}
		if ov.DeleteRequested != nil {
			if eq, handled := ov.DeleteRequested(x, y); handled {
				return eq
			}
		}
		if x.Id != y.Id {
			return false
		}
		return true
	case FilterRequested:
		y, ok := any(b).(FilterRequested)
		if !ok {
			return false
		}
		if ov.FilterRequested != nil {
			if eq, handled := ov.FilterRequested(x, y); handled {
				return eq
			}
		}
		if !FilterEqual(x.Filter, y.Filter) {
			return false
		}
		return true
	case SaveSucceeded:
		y, ok := any(b).(SaveSucceeded)
		if !ok {
			return false
		}
		if ov.SaveSucceeded != nil {
			if eq, handled := ov.SaveSucceeded(x, y); handled {
				return eq
			}
		}
		if len(x.Tasks) != len(y.Tasks) {
			return false
		}
		for i0 := range x.Tasks {
			if x.Tasks[i0] != y.Tasks[i0] {
				return false
			}
		}
		return true
	case SaveFailed:
		y, ok := any(b).(SaveFailed)
		if !ok {
			return false
		}
		if ov.SaveFailed != nil {
			if eq, handled := ov.SaveFailed(x, y); handled {
				return eq
			}
		}
		if x.Message != y.Message {
			return false
		}
		return true
	}
	return false
}

// MsgEqual reports structural equality of a and b.
func MsgEqual(a, b Msg) bool {
	return MsgEqualWith(a, b, MsgEqOverrides{})
}

type Bootstrap struct {
	Initial Model
}

type modelWire struct {
	Tasks  []Task `json:"tasks"`
	Draft  string `json:"draft"`
	Filter string `json:"filter"`
	Saving bool   `json:"saving"`
	Error  string `json:"error"`
	NextID int    `json:"next_id"`
}

type messageWire struct {
	Type    string `json:"type"`
	Value   string `json:"value,omitempty"`
	ID      int    `json:"id,omitempty"`
	Filter  string `json:"filter,omitempty"`
	Tasks   []Task `json:"tasks,omitempty"`
	Message string `json:"message,omitempty"`
}

func InitialModel() Model {
	return Model{
		Tasks: []Task{
			{ID: 1, Title: "Define the shared model"},
			{ID: 2, Title: "Hydrate browser and native views"},
		},
		Filter: FilterAll{},
		NextID: 3,
	}
}

func ModelCodec() program.Codec[Model] {
	return program.Codec[Model]{
		Encode: func(model Model) ([]byte, error) {
			return json.Marshal(modelWire{
				Tasks:  cloneTasks(model.Tasks),
				Draft:  model.Draft,
				Filter: filterName(model.Filter),
				Saving: model.Saving,
				Error:  model.Error,
				NextID: model.NextID,
			})
		},
		Decode: func(data []byte) (Model, error) {
			var wire modelWire
			if err := json.Unmarshal(data, &wire); err != nil {
				return Model{}, err
			}
			filter, err := parseFilter(wire.Filter)
			if err != nil {
				return Model{}, err
			}
			return Model{
				Tasks:  cloneTasks(wire.Tasks),
				Draft:  wire.Draft,
				Filter: filter,
				Saving: wire.Saving,
				Error:  wire.Error,
				NextID: wire.NextID,
			}, nil
		},
	}
}

func MessageCodec() program.Codec[Msg] {
	return program.Codec[Msg]{
		Encode: encodeMessage,
		Decode: decodeMessage,
	}
}

func encodeMessage(message Msg) ([]byte, error) {
	var wire messageWire
	switch __gp_m0 := any(message).(type) {
	case DraftChanged:
		value := __gp_m0.Value

		wire = messageWire{Type: "draft-changed", Value: value}
	case AddRequested:

		wire = messageWire{Type: "add-requested"}
	case ToggleRequested:
		id := __gp_m0.Id

		wire = messageWire{Type: "toggle-requested", ID: id}
	case DeleteRequested:
		id := __gp_m0.Id

		wire = messageWire{Type: "delete-requested", ID: id}
	case FilterRequested:
		filter := __gp_m0.Filter

		wire = messageWire{Type: "filter-requested", Filter: filterName(filter)}
	case SaveSucceeded:
		tasks := __gp_m0.Tasks

		wire = messageWire{Type: "save-succeeded", Tasks: cloneTasks(tasks)}
	case SaveFailed:
		message := __gp_m0.Message

		wire = messageWire{Type: "save-failed", Message: message}
	default:
		panic("goplus: impossible enum value in match")
	}
	return json.Marshal(wire)
}

func decodeMessage(data []byte) (Msg, error) {
	var wire messageWire
	if err := json.Unmarshal(data, &wire); err != nil {
		return nil, err
	}
	switch wire.Type {
	case "draft-changed":
		return DraftChanged{Value: wire.Value}, nil
	case "add-requested":
		return AddRequested{}, nil
	case "toggle-requested":
		return ToggleRequested{Id: wire.ID}, nil
	case "delete-requested":
		return DeleteRequested{Id: wire.ID}, nil
	case "filter-requested":
		filter, err := parseFilter(wire.Filter)
		if err != nil {
			return nil, err
		}
		return FilterRequested{Filter: filter}, nil
	case "save-succeeded":
		return SaveSucceeded{Tasks: cloneTasks(wire.Tasks)}, nil
	case "save-failed":
		return SaveFailed{Message: wire.Message}, nil
	default:
		return nil, fmt.Errorf("taskboard: unknown message %q", wire.Type)
	}
}

func filterName(filter Filter) string {
	return FilterFold(filter, FilterCases[string]{
		FilterAll:       func() string { return "all" },
		FilterActive:    func() string { return "active" },
		FilterCompleted: func() string { return "completed" },
	})
}

func parseFilter(value string) (Filter, error) {
	switch value {
	case "", "all":
		return FilterAll{}, nil
	case "active":
		return FilterActive{}, nil
	case "completed":
		return FilterCompleted{}, nil
	default:
		return nil, fmt.Errorf("taskboard: invalid filter %q", value)
	}
}

func cloneTasks(tasks []Task) []Task {
	return append([]Task(nil), tasks...)
}
