// Code generated by goplus from main.gp. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"log"

	taskboard "goforge.dev/cadence-taskboard"
	bubbletea "goforge.dev/quicken/tui"
)

func main() {
	_, err := bubbletea.Run(
		taskboard.Logic(taskboard.InitialModel(), taskboard.LocalSave),
		bubbletea.SELView(taskboard.SemanticView, bubbletea.DefaultPalette()),
		nil,
		nil,
	)
	if err != nil {
		log.Fatal(err)
	}
}
