// Code generated by goplus from executor.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"sync"
	"time"

	"goforge.dev/cadence/program"
)

// EffectHandler executes one GUI or application-specific effect and calls
// complete exactly once. The returned function cancels in-flight work.
type EffectHandler[Msg any] interface {
	Execute(program.Cmd[Msg], program.Dispatch[Msg], func()) func()
}

type EffectHandlerFunc[Msg any] func(
	program.Cmd[Msg],
	program.Dispatch[Msg],
	func(),
) func()

func (f EffectHandlerFunc[Msg]) Execute(
	command program.Cmd[Msg],
	dispatch program.Dispatch[Msg],
	complete func(),
) func() {
	return f(command, dispatch, complete)
}

type Executor[Msg any] struct {
	handler EffectHandler[Msg]
	mu      sync.Mutex
	cancel  map[string]func()
}

func NewExecutor[Msg any](handler EffectHandler[Msg]) *Executor[Msg] {
	return &Executor[Msg]{handler: handler, cancel: map[string]func(){}}
}

func (e *Executor[Msg]) Execute(command program.Cmd[Msg], dispatch program.Dispatch[Msg]) {
	e.run(command, dispatch, func() {})
}

func (e *Executor[Msg]) run(
	command program.Cmd[Msg],
	dispatch program.Dispatch[Msg],
	complete func(),
) {
	switch program.CommandKindName(command.Kind()) {
	case "none":
		complete()
	case "emit":
		dispatch(command.Message())
		complete()
	case "batch":
		children := command.Commands()
		if len(children) == 0 {
			complete()
			return
		}
		var mu sync.Mutex
		remaining := len(children)
		for _, child := range children {
			current := child
			go e.run(current, dispatch, func() {
				mu.Lock()
				remaining--
				last := remaining == 0
				mu.Unlock()
				if last {
					complete()
				}
			})
		}
	case "sequence":
		e.sequence(command.Commands(), dispatch, complete)
	case "after":
		children := command.Commands()
		if len(children) == 0 {
			complete()
			return
		}
		timer := time.AfterFunc(command.Delay(), func() {
			e.clear(command.Key())
			e.run(children[0], dispatch, complete)
		})
		e.install(command.Key(), func() {
			timer.Stop()
			complete()
		})
	case "cancel":
		e.cancelKey(command.Key())
		complete()
	case "effect":
		if e.handler == nil {
			complete()
			return
		}
		cancel := e.handler.Execute(command, dispatch, func() {
			e.clear(command.Key())
			complete()
		})
		e.install(command.Key(), cancel)
	default:
		complete()
	}
}

func (e *Executor[Msg]) sequence(
	commands []program.Cmd[Msg],
	dispatch program.Dispatch[Msg],
	complete func(),
) {
	if len(commands) == 0 {
		complete()
		return
	}
	e.run(commands[0], dispatch, func() {
		e.sequence(commands[1:], dispatch, complete)
	})
}

func (e *Executor[Msg]) install(key string, cancel func()) {
	if key == "" || cancel == nil {
		return
	}
	e.mu.Lock()
	previous := e.cancel[key]
	e.cancel[key] = cancel
	e.mu.Unlock()
	if previous != nil {
		previous()
	}
}

func (e *Executor[Msg]) clear(key string) {
	if key == "" {
		return
	}
	e.mu.Lock()
	delete(e.cancel, key)
	e.mu.Unlock()
}

func (e *Executor[Msg]) cancelKey(key string) {
	if key == "" {
		return
	}
	e.mu.Lock()
	cancel := e.cancel[key]
	delete(e.cancel, key)
	e.mu.Unlock()
	if cancel != nil {
		cancel()
	}
}
