// Code generated by goplus from sel.gp. DO NOT EDIT.
//goplus:v v0.28.0

package native

import (
	"fmt"
	"strings"

	"gioui.org/layout"
	"gioui.org/unit"
	"gioui.org/widget/material"
	"goforge.dev/cadence/sel"
)

func SELView[State any, Msg any](
	render func(State) sel.Element[Msg],
	palette Palette,
) View[State, Msg] {
	return SELViewWithIdiom(render, palette, DesktopIdiom())
}

func SELViewWithIdiom[State any, Msg any](
	render func(State) sel.Element[Msg],
	palette Palette,
	idiom Idiom,
) View[State, Msg] {
	return func(gtx layout.Context, state State, ui *UI[Msg]) layout.Dimensions {
		root := render(state)
		if err := sel.Validate(root, sel.TargetGio{}); err != nil {
			return material.Body1(ui.Theme, "render error: "+err.Error()).Layout(gtx)
		}
		return elementWidget(root, ui, palette, idiom)(gtx)
	}
}

func elementWidget[Msg any](
	element sel.Element[Msg],
	ui *UI[Msg],
	palette Palette,
	idiom Idiom,
) layout.Widget {
	children := make([]layout.Widget, 0, len(element.Children))
	for _, child := range element.Children {
		children = append(children, elementWidget(child, ui, palette, idiom))
	}
	content := func(gtx layout.Context) layout.Dimensions {
		name := sel.KindName(element.Kind)
		switch name {
		case "text", "status":
			label := material.Body1(ui.Theme, element.Text)
			label.Color = ColorFor(element.Style.Foreground, palette)
			return label.Layout(gtx)
		case "heading":
			label := material.H6(ui.Theme, element.Text)
			label.Color = ColorFor(element.Style.Foreground, palette)
			return label.Layout(gtx)
		case "button":
			if message, ok := eventMessage(element.Events, "activate"); ok {
				return ui.Button(gtx, semanticKey(element), childText(element), message)
			}
			return ui.Label(gtx, childText(element))
		case "link":
			if message, ok := eventMessage(element.Events, "activate"); ok {
				return ui.Button(gtx, semanticKey(element), childText(element), message)
			}
			return ui.Label(gtx, childText(element)+" <"+element.Attributes["href"]+">")
		case "text-input", "text-area":
			decode := inputDecoder(element.Events)
			return ui.Editor(
				gtx, semanticKey(element), element.Value, element.Description,
				name == "text-input", decode,
			)
		case "checkbox":
			if message, ok := eventMessage(element.Events, "change"); ok {
				return ui.Checkbox(
					gtx, semanticKey(element), childText(element),
					element.Checked, message,
				)
			}
			return ui.Label(gtx, childText(element))
		case "row":
			return flexLayout(gtx, layout.Horizontal, children, idiom.Gap)
		case "paragraph", "column", "stack", "scroll", "form", "list", "table":
			return flexLayout(gtx, layout.Vertical, children, idiom.Gap)
		case "image":
			return ui.Label(gtx, "[image: "+element.Description+"]")
		case "progress":
			return ui.Label(gtx, fmt.Sprintf(
				"%s %s/%s",
				element.Description,
				element.Attributes["value"],
				element.Attributes["max"],
			))
		case "select":
			return ui.Label(gtx, element.Description+": "+element.Value)
		default:
			return flexLayout(gtx, layout.Vertical, children, idiom.Gap)
		}
	}
	return func(gtx layout.Context) layout.Dimensions {
		name := sel.KindName(element.Kind)
		if name == "button" || name == "link" || name == "text-input" ||
			name == "text-area" || name == "checkbox" || name == "select" {
			height := gtx.Dp(idiom.MinimumControlHeight)
			if gtx.Constraints.Min.Y < height {
				gtx.Constraints.Min.Y = height
			}
		}
		return Styled(gtx, element.Style, palette, content)
	}
}

func flexLayout(
	gtx layout.Context,
	axis layout.Axis,
	children []layout.Widget,
	gap unit.Dp,
) layout.Dimensions {
	items := make([]layout.FlexChild, 0, len(children))
	for _, child := range children {
		current := child
		items = append(items, layout.Rigid(current))
	}
	return layout.Flex{Axis: axis, Gap: gtx.Dp(gap)}.Layout(gtx, items...)
}

func eventMessage[Msg any](events []sel.Event[Msg], want string) (Msg, bool) {
	for _, event := range events {
		if selEventKindName(event.Kind) == want {
			return event.Message, true
		}
	}
	var zero Msg
	return zero, false
}

func inputDecoder[Msg any](events []sel.Event[Msg]) func(string) Msg {
	for _, event := range events {
		if (selEventKindName(event.Kind) == "input" ||
			selEventKindName(event.Kind) == "change") &&
			event.Decode != nil {
			return event.Decode
		}
	}
	return nil
}

func selEventKindName(kind sel.EventKind) string {
	return sel.EventKindFold(kind, sel.EventKindCases[string]{
		EventActivate: func() string { return "activate" },
		EventInput:    func() string { return "input" },
		EventChange:   func() string { return "change" },
		EventSubmit:   func() string { return "submit" },
		EventFocus:    func() string { return "focus" },
		EventBlur:     func() string { return "blur" },
	})
}

func semanticKey[Msg any](element sel.Element[Msg]) string {
	if element.Key != "" {
		return element.Key
	}
	return sel.KindName(element.Kind) + ":" + element.Description + ":" + element.Text
}

func childText[Msg any](element sel.Element[Msg]) string {
	var out strings.Builder
	for _, child := range element.Children {
		out.WriteString(child.Text)
	}
	return out.String()
}
