// Code generated by goplus from main.gp. DO NOT EDIT.
//goplus:v v0.28.0

package main

import (
	"log"

	"gioui.org/unit"
	taskboard "goforge.dev/cadence-taskboard"
	desktop "goforge.dev/quicken/desktop"
	native "goforge.dev/quicken/native"
)

func main() {
	_, err := desktop.Run(desktop.Application[taskboard.Model, taskboard.Msg]{
		Logic: taskboard.Logic(taskboard.InitialModel(), taskboard.LocalSave),
		View:  native.SELView(taskboard.SemanticView, native.DefaultPalette()),
		Window: native.WindowOptions{
			Title:  "ForgeFlow Operations",
			Width:  unit.Dp(720),
			Height: unit.Dp(540),
		},
	})
	if err != nil {
		log.Fatal(err)
	}
}
