// Code generated by goplus from live_js.gp. DO NOT EDIT.
//goplus:v v0.28.0

//go:build js && wasm

package dom

import (
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
	"sync"
	"syscall/js"
	"time"

	"goforge.dev/cadence/program"
	browser "goforge.dev/quicken/web/browser"
)

type LiveClient[Model any, Msg any] struct {
	mu           sync.Mutex
	manifest     browser.Manifest
	runtime      *Runtime[Model, Msg]
	modelCodec   program.Codec[Model]
	messageCodec program.Codec[Msg]
	socket       js.Value
	callbacks    []js.Func
	pollAbort    js.Value
	revision     uint64
	sequence     uint64
	closed       bool
	polling      bool
	connecting   bool
}

func MountLive[Model any, Msg any](
	options Options[Model, Msg],
	modelCodec program.Codec[Model],
	messageCodec program.Codec[Msg],
) (*Runtime[Model, Msg], *LiveClient[Model, Msg], error) {
	runtime, err := Mount(options)
	if err != nil {
		return nil, nil, err
	}
	client, err := NewLiveClient(options.Manifest, runtime, modelCodec, messageCodec)
	if err != nil {
		runtime.Unmount()
		return nil, nil, err
	}
	runtime.SetMessageSink(client.Send)
	originalUnmount := runtime.unmount
	runtime.unmount = func() {
		client.Close()
		originalUnmount()
	}
	if err := client.Connect(); err != nil {
		runtime.Unmount()
		return nil, nil, err
	}
	return runtime, client, nil
}

func NewLiveClient[Model any, Msg any](
	manifest browser.Manifest,
	runtime *Runtime[Model, Msg],
	modelCodec program.Codec[Model],
	messageCodec program.Codec[Msg],
) (*LiveClient[Model, Msg], error) {
	if err := manifest.Validate(); err != nil {
		return nil, err
	}
	if runtime == nil || modelCodec.Decode == nil || messageCodec.Encode == nil {
		return nil, fmt.Errorf("quicken/web/browser/dom: live runtime and codecs are required")
	}
	if manifest.Endpoints.Socket == "" || manifest.Endpoints.LongPoll == "" ||
		manifest.Endpoints.Event == "" || manifest.ResumeToken == "" {
		return nil, fmt.Errorf("quicken/web/browser/dom: live endpoints and resume token are required")
	}
	return &LiveClient[Model, Msg]{
		manifest:     manifest,
		runtime:      runtime,
		modelCodec:   modelCodec,
		messageCodec: messageCodec,
		revision:     manifest.InitialRevision,
	}, nil
}

func (c *LiveClient[Model, Msg]) Connect() error {
	c.mu.Lock()
	if c.closed {
		c.mu.Unlock()
		return fmt.Errorf("quicken/web/browser/dom: live client is closed")
	}
	if c.connecting || socketOpen(c.socket) {
		c.mu.Unlock()
		return nil
	}
	c.connecting = true
	c.mu.Unlock()

	socketURL, err := websocketURL(c.manifest.Endpoints.Socket)
	if err != nil {
		c.mu.Lock()
		c.connecting = false
		c.mu.Unlock()
		return err
	}
	socket := js.Global().Get("WebSocket").New(socketURL)
	open := js.FuncOf(func(this js.Value, args []js.Value) any {
		c.mu.Lock()
		c.socket = socket
		c.connecting = false
		c.stopPollingLocked()
		c.mu.Unlock()
		c.sendEnvelope(browser.LiveClientEnvelope{
			ProtocolVersion: browser.LiveProtocolVersion,
			Type:            browser.LiveResumeType,
			AppID:           c.manifest.AppID,
			ProgramID:       c.manifest.ProgramID,
			InstanceID:      c.manifest.InstanceID,
			Token:           c.manifest.ResumeToken,
			Revision:        c.currentRevision(),
		})
		return nil
	})
	message := js.FuncOf(func(this js.Value, args []js.Value) any {
		c.receive(args[0].Get("data").String())
		return nil
	})
	closeCallback := js.FuncOf(func(this js.Value, args []js.Value) any {
		c.mu.Lock()
		c.socket = js.Undefined()
		c.connecting = false
		closed := c.closed
		c.mu.Unlock()
		if !closed {
			c.startPolling()
			time.AfterFunc(2*time.Second, func() { _ = c.Connect() })
		}
		return nil
	})
	errorCallback := js.FuncOf(func(this js.Value, args []js.Value) any {
		socket.Call("close")
		return nil
	})
	socket.Set("onopen", open)
	socket.Set("onmessage", message)
	socket.Set("onclose", closeCallback)
	socket.Set("onerror", errorCallback)
	c.mu.Lock()
	c.socket = socket
	c.callbacks = append(c.callbacks, open, message, closeCallback, errorCallback)
	c.mu.Unlock()
	return nil
}

func (c *LiveClient[Model, Msg]) Send(message Msg) {
	encoded, err := c.messageCodec.Encode(message)
	if err != nil {
		return
	}
	envelope := browser.LiveClientEnvelope{
		ProtocolVersion: browser.LiveProtocolVersion,
		Type:            browser.LiveEventType,
		AppID:           c.manifest.AppID,
		ProgramID:       c.manifest.ProgramID,
		InstanceID:      c.manifest.InstanceID,
		Token:           c.manifest.ResumeToken,
		RequestID:       c.nextRequestID(),
		Revision:        c.currentRevision(),
		Message:         encoded,
	}
	c.mu.Lock()
	open := socketOpen(c.socket)
	c.mu.Unlock()
	if open {
		c.sendEnvelope(envelope)
		return
	}
	go c.postEvent(envelope)
}

func (c *LiveClient[Model, Msg]) receive(raw string) {
	var envelope browser.LiveServerEnvelope
	if json.Unmarshal([]byte(raw), &envelope) != nil || envelope.Validate() != nil {
		return
	}
	if envelope.AppID != c.manifest.AppID ||
		envelope.ProgramID != c.manifest.ProgramID ||
		envelope.InstanceID != c.manifest.InstanceID {
		return
	}
	c.setRevision(envelope.Revision)
	if envelope.Type != browser.LiveSnapshotType {
		return
	}
	model, err := c.modelCodec.Decode(envelope.Model)
	if err != nil {
		return
	}
	c.runtime.Synchronize(model)
}

func (c *LiveClient[Model, Msg]) sendEnvelope(envelope browser.LiveClientEnvelope) {
	encoded, err := json.Marshal(envelope)
	if err != nil {
		return
	}
	c.mu.Lock()
	socket := c.socket
	open := socketOpen(socket)
	c.mu.Unlock()
	if open {
		socket.Call("send", string(encoded))
	}
}

func (c *LiveClient[Model, Msg]) postEvent(envelope browser.LiveClientEnvelope) {
	encoded, err := json.Marshal(envelope)
	if err != nil {
		return
	}
	options := map[string]any{
		"method": "POST",
		"headers": map[string]any{
			"Content-Type":   "application/json",
			"X-Cadence-CSRF": csrfCookie(),
		},
		"body":        string(encoded),
		"credentials": "same-origin",
	}
	_, _ = awaitPromise(js.Global().Call(
		"fetch",
		c.manifest.Endpoints.Event,
		js.ValueOf(options),
	))
}

func (c *LiveClient[Model, Msg]) startPolling() {
	c.mu.Lock()
	if c.closed || c.polling {
		c.mu.Unlock()
		return
	}
	c.polling = true
	c.mu.Unlock()
	go c.pollLoop()
}

func (c *LiveClient[Model, Msg]) pollLoop() {
	for {
		c.mu.Lock()
		if c.closed || !c.polling || socketOpen(c.socket) {
			c.polling = false
			c.mu.Unlock()
			return
		}
		controller := js.Global().Get("AbortController").New()
		c.pollAbort = controller
		revision := c.revision
		c.mu.Unlock()

		endpoint := c.manifest.Endpoints.LongPoll +
			"?token=" + url.QueryEscape(c.manifest.ResumeToken) +
			"&revision=" + strconv.FormatUint(revision, 10)
		response, err := awaitPromise(js.Global().Call(
			"fetch",
			endpoint,
			js.ValueOf(map[string]any{
				"credentials": "same-origin",
				"cache":       "no-store",
				"signal":      controller.Get("signal"),
			}),
		))
		if err != nil {
			time.Sleep(time.Second)
			continue
		}
		if response.Get("status").Int() == httpStatusNoContent {
			continue
		}
		if !response.Get("ok").Bool() {
			time.Sleep(time.Second)
			continue
		}
		value, err := awaitPromise(response.Call("text"))
		if err == nil {
			c.receive(value.String())
		}
	}
}

const httpStatusNoContent = 204

func (c *LiveClient[Model, Msg]) Close() {
	c.mu.Lock()
	if c.closed {
		c.mu.Unlock()
		return
	}
	c.closed = true
	c.stopPollingLocked()
	socket := c.socket
	callbacks := append([]js.Func(nil), c.callbacks...)
	c.callbacks = nil
	c.mu.Unlock()
	if socketOpen(socket) || socketConnecting(socket) {
		socket.Call("close")
	}
	for _, callback := range callbacks {
		callback.Release()
	}
}

func (c *LiveClient[Model, Msg]) stopPollingLocked() {
	c.polling = false
	if c.pollAbort.Type() != js.TypeUndefined && c.pollAbort.Type() != js.TypeNull {
		c.pollAbort.Call("abort")
		c.pollAbort = js.Undefined()
	}
}

func (c *LiveClient[Model, Msg]) currentRevision() uint64 {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.revision
}

func (c *LiveClient[Model, Msg]) setRevision(revision uint64) {
	c.mu.Lock()
	defer c.mu.Unlock()
	if revision > c.revision {
		c.revision = revision
	}
}

func (c *LiveClient[Model, Msg]) nextRequestID() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	c.sequence++
	return c.manifest.InstanceID + "-" + strconv.FormatUint(c.sequence, 10)
}

func socketOpen(socket js.Value) bool {
	return socket.Type() != js.TypeUndefined && socket.Type() != js.TypeNull &&
		socket.Get("readyState").Int() == 1
}

func socketConnecting(socket js.Value) bool {
	return socket.Type() != js.TypeUndefined && socket.Type() != js.TypeNull &&
		socket.Get("readyState").Int() == 0
}

func websocketURL(endpoint string) (string, error) {
	base := js.Global().Get("document").Get("baseURI").String()
	value := js.Global().Get("URL").New(endpoint, base)
	protocol := value.Get("protocol").String()
	switch protocol {
	case "http:":
		value.Set("protocol", "ws:")
	case "https:":
		value.Set("protocol", "wss:")
	case "ws:", "wss:":
	default:
		return "", fmt.Errorf("quicken/web/browser/dom: invalid WebSocket endpoint")
	}
	return value.String(), nil
}
