// Code generated by goplus from app.gp. DO NOT EDIT.
//goplus:v v0.28.0

package desktop

import (
	"gioui.org/widget/material"
	"goforge.dev/cadence/program"
	native "goforge.dev/quicken/native"
)

type Application[Model, Msg any] struct {
	Logic   program.Logic[Model, Msg]
	View    native.View[Model, Msg]
	Effects native.EffectHandler[Msg]
	Theme   *material.Theme
	Window  native.WindowOptions
}

func Run[Model, Msg any](application Application[Model, Msg]) (Model, error) {
	window := native.NewWindow(application.Window)
	type result struct {
		model Model
		err   error
	}
	done := make(chan result, 1)
	go func() {
		model, err := native.RunWindow(
			window,
			application.Logic,
			application.View,
			application.Effects,
			application.Theme,
		)
		done <- result{model: model, err: err}
	}()
	native.Main()
	out := <-done
	return out.model, out.err
}
