// Code generated by goplus from doc.gp. DO NOT EDIT.
//goplus:v v0.28.0

// Package desktop runs Cadence programs as native Windows, macOS, and Linux
// applications through Quicken Native and Gio.
package desktop
